// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: locale.proto

package com.tiwari.studence.proto.locale;

/**
 * Protobuf type {@code com.tiwari.studence.proto.locale.LocaleInfoUiPb}
 */
public final class LocaleInfoUiPb extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.tiwari.studence.proto.locale.LocaleInfoUiPb)
    LocaleInfoUiPbOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LocaleInfoUiPb.newBuilder() to construct.
  private LocaleInfoUiPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LocaleInfoUiPb() {
    locale_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LocaleInfoUiPb();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tiwari.studence.proto.locale.Locale.internal_static_com_tiwari_studence_proto_locale_LocaleInfoUiPb_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tiwari.studence.proto.locale.Locale.internal_static_com_tiwari_studence_proto_locale_LocaleInfoUiPb_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tiwari.studence.proto.locale.LocaleInfoUiPb.class, com.tiwari.studence.proto.locale.LocaleInfoUiPb.Builder.class);
  }

  private int bitField0_;
  public static final int LOCALE_FIELD_NUMBER = 1;
  private int locale_ = 0;
  /**
   * <code>optional .com.tiwari.studence.proto.locale.LocaleUiEnum locale = 1;</code>
   * @return Whether the locale field is set.
   */
  @java.lang.Override public boolean hasLocale() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .com.tiwari.studence.proto.locale.LocaleUiEnum locale = 1;</code>
   * @return The enum numeric value on the wire for locale.
   */
  @java.lang.Override public int getLocaleValue() {
    return locale_;
  }
  /**
   * <code>optional .com.tiwari.studence.proto.locale.LocaleUiEnum locale = 1;</code>
   * @return The locale.
   */
  @java.lang.Override public com.tiwari.studence.proto.locale.LocaleUiEnum getLocale() {
    com.tiwari.studence.proto.locale.LocaleUiEnum result = com.tiwari.studence.proto.locale.LocaleUiEnum.forNumber(locale_);
    return result == null ? com.tiwari.studence.proto.locale.LocaleUiEnum.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeEnum(1, locale_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, locale_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tiwari.studence.proto.locale.LocaleInfoUiPb)) {
      return super.equals(obj);
    }
    com.tiwari.studence.proto.locale.LocaleInfoUiPb other = (com.tiwari.studence.proto.locale.LocaleInfoUiPb) obj;

    if (hasLocale() != other.hasLocale()) return false;
    if (hasLocale()) {
      if (locale_ != other.locale_) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasLocale()) {
      hash = (37 * hash) + LOCALE_FIELD_NUMBER;
      hash = (53 * hash) + locale_;
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tiwari.studence.proto.locale.LocaleInfoUiPb parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tiwari.studence.proto.locale.LocaleInfoUiPb parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tiwari.studence.proto.locale.LocaleInfoUiPb parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tiwari.studence.proto.locale.LocaleInfoUiPb parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tiwari.studence.proto.locale.LocaleInfoUiPb parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tiwari.studence.proto.locale.LocaleInfoUiPb parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tiwari.studence.proto.locale.LocaleInfoUiPb parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tiwari.studence.proto.locale.LocaleInfoUiPb parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tiwari.studence.proto.locale.LocaleInfoUiPb parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tiwari.studence.proto.locale.LocaleInfoUiPb parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tiwari.studence.proto.locale.LocaleInfoUiPb parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tiwari.studence.proto.locale.LocaleInfoUiPb parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tiwari.studence.proto.locale.LocaleInfoUiPb prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.tiwari.studence.proto.locale.LocaleInfoUiPb}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.tiwari.studence.proto.locale.LocaleInfoUiPb)
      com.tiwari.studence.proto.locale.LocaleInfoUiPbOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tiwari.studence.proto.locale.Locale.internal_static_com_tiwari_studence_proto_locale_LocaleInfoUiPb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tiwari.studence.proto.locale.Locale.internal_static_com_tiwari_studence_proto_locale_LocaleInfoUiPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tiwari.studence.proto.locale.LocaleInfoUiPb.class, com.tiwari.studence.proto.locale.LocaleInfoUiPb.Builder.class);
    }

    // Construct using com.tiwari.studence.proto.locale.LocaleInfoUiPb.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      locale_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tiwari.studence.proto.locale.Locale.internal_static_com_tiwari_studence_proto_locale_LocaleInfoUiPb_descriptor;
    }

    @java.lang.Override
    public com.tiwari.studence.proto.locale.LocaleInfoUiPb getDefaultInstanceForType() {
      return com.tiwari.studence.proto.locale.LocaleInfoUiPb.getDefaultInstance();
    }

    @java.lang.Override
    public com.tiwari.studence.proto.locale.LocaleInfoUiPb build() {
      com.tiwari.studence.proto.locale.LocaleInfoUiPb result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tiwari.studence.proto.locale.LocaleInfoUiPb buildPartial() {
      com.tiwari.studence.proto.locale.LocaleInfoUiPb result = new com.tiwari.studence.proto.locale.LocaleInfoUiPb(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.tiwari.studence.proto.locale.LocaleInfoUiPb result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.locale_ = locale_;
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tiwari.studence.proto.locale.LocaleInfoUiPb) {
        return mergeFrom((com.tiwari.studence.proto.locale.LocaleInfoUiPb)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tiwari.studence.proto.locale.LocaleInfoUiPb other) {
      if (other == com.tiwari.studence.proto.locale.LocaleInfoUiPb.getDefaultInstance()) return this;
      if (other.hasLocale()) {
        setLocale(other.getLocale());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              locale_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int locale_ = 0;
    /**
     * <code>optional .com.tiwari.studence.proto.locale.LocaleUiEnum locale = 1;</code>
     * @return Whether the locale field is set.
     */
    @java.lang.Override public boolean hasLocale() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .com.tiwari.studence.proto.locale.LocaleUiEnum locale = 1;</code>
     * @return The enum numeric value on the wire for locale.
     */
    @java.lang.Override public int getLocaleValue() {
      return locale_;
    }
    /**
     * <code>optional .com.tiwari.studence.proto.locale.LocaleUiEnum locale = 1;</code>
     * @param value The enum numeric value on the wire for locale to set.
     * @return This builder for chaining.
     */
    public Builder setLocaleValue(int value) {
      locale_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional .com.tiwari.studence.proto.locale.LocaleUiEnum locale = 1;</code>
     * @return The locale.
     */
    @java.lang.Override
    public com.tiwari.studence.proto.locale.LocaleUiEnum getLocale() {
      com.tiwari.studence.proto.locale.LocaleUiEnum result = com.tiwari.studence.proto.locale.LocaleUiEnum.forNumber(locale_);
      return result == null ? com.tiwari.studence.proto.locale.LocaleUiEnum.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .com.tiwari.studence.proto.locale.LocaleUiEnum locale = 1;</code>
     * @param value The locale to set.
     * @return This builder for chaining.
     */
    public Builder setLocale(com.tiwari.studence.proto.locale.LocaleUiEnum value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      locale_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .com.tiwari.studence.proto.locale.LocaleUiEnum locale = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLocale() {
      bitField0_ = (bitField0_ & ~0x00000001);
      locale_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.tiwari.studence.proto.locale.LocaleInfoUiPb)
  }

  // @@protoc_insertion_point(class_scope:com.tiwari.studence.proto.locale.LocaleInfoUiPb)
  private static final com.tiwari.studence.proto.locale.LocaleInfoUiPb DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tiwari.studence.proto.locale.LocaleInfoUiPb();
  }

  public static com.tiwari.studence.proto.locale.LocaleInfoUiPb getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LocaleInfoUiPb>
      PARSER = new com.google.protobuf.AbstractParser<LocaleInfoUiPb>() {
    @java.lang.Override
    public LocaleInfoUiPb parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LocaleInfoUiPb> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LocaleInfoUiPb> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tiwari.studence.proto.locale.LocaleInfoUiPb getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

