// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: locale.proto

package com.tiwari.studence.proto.locale;

public final class Locale {
  private Locale() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tiwari_studence_proto_locale_LocaleUiPb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tiwari_studence_proto_locale_LocaleUiPb_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tiwari_studence_proto_locale_LocalePb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tiwari_studence_proto_locale_LocalePb_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tiwari_studence_proto_locale_LocaleInfoPb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tiwari_studence_proto_locale_LocaleInfoPb_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tiwari_studence_proto_locale_LocaleInfoUiPb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tiwari_studence_proto_locale_LocaleInfoUiPb_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014locale.proto\022 com.tiwari.studence.prot" +
      "o.locale\032\014timePb.proto\032\021mergeOption.prot" +
      "o\"\203\003\n\nLocaleUiPb\022E\n\013localesInfo\030\001 \003(\01320." +
      "com.tiwari.studence.proto.locale.LocaleI" +
      "nfoUiPb\022P\n\021defaultLocaleInfo\030\002 \001(\01320.com" +
      ".tiwari.studence.proto.locale.LocaleInfo" +
      "UiPbH\000\210\001\001\022P\n\021currentLocaleInfo\030\003 \001(\01320.c" +
      "om.tiwari.studence.proto.locale.LocaleIn" +
      "foUiPbH\001\210\001\001\022J\n\017defaultTimeZone\030\004 \001(\0162,.c" +
      "om.tiwari.studence.proto.time.TimezoneEn" +
      "umH\002\210\001\001B\024\n\022_defaultLocaleInfoB\024\n\022_curren" +
      "tLocaleInfoB\022\n\020_defaultTimeZone\"\225\002\n\010Loca" +
      "lePb\022C\n\013localesInfo\030\001 \003(\0132..com.tiwari.s" +
      "tudence.proto.locale.LocaleInfoPb\022N\n\021def" +
      "aultLocaleInfo\030\002 \001(\0132..com.tiwari.studen" +
      "ce.proto.locale.LocaleInfoPbH\000\210\001\001\022J\n\017def" +
      "aultTimeZone\030\004 \001(\0162,.com.tiwari.studence" +
      ".proto.time.TimezoneEnumH\001\210\001\001B\024\n\022_defaul" +
      "tLocaleInfoB\022\n\020_defaultTimeZone\"e\n\014Local" +
      "eInfoPb\022C\n\006locale\030\001 \001(\0162..com.tiwari.stu" +
      "dence.proto.locale.LocaleUiEnumH\000\210\001\001:\005\222\202" +
      "\031\0011B\t\n\007_locale\"`\n\016LocaleInfoUiPb\022C\n\006loca" +
      "le\030\001 \001(\0162..com.tiwari.studence.proto.loc" +
      "ale.LocaleUiEnumH\000\210\001\001B\t\n\007_locale*\223\001\n\014Loc" +
      "aleUiEnum\022\022\n\016UNKNOWN_LOCALE\020\000\022\t\n\005en_IN\020\001" +
      "\022\t\n\005hi_IN\020\002\022\t\n\005bn_IN\020\003\022\006\n\002ar\020\004\022\006\n\002en\020\005\022\006" +
      "\n\002te\020\006\022\006\n\002ta\020\007\022\006\n\002kn\020\010\022\006\n\002or\020\t\022\006\n\002ks\020\n\022\006" +
      "\n\002pa\020\013\022\006\n\002ur\020\014\022\006\n\002mr\020\rB\005P\001\240\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.tiwari.studence.proto.time.TimePbOuterClass.getDescriptor(),
          com.tiwari.studence.proto.mergeOption.MergeOption.getDescriptor(),
        });
    internal_static_com_tiwari_studence_proto_locale_LocaleUiPb_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_tiwari_studence_proto_locale_LocaleUiPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tiwari_studence_proto_locale_LocaleUiPb_descriptor,
        new java.lang.String[] { "LocalesInfo", "DefaultLocaleInfo", "CurrentLocaleInfo", "DefaultTimeZone", "DefaultLocaleInfo", "CurrentLocaleInfo", "DefaultTimeZone", });
    internal_static_com_tiwari_studence_proto_locale_LocalePb_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_tiwari_studence_proto_locale_LocalePb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tiwari_studence_proto_locale_LocalePb_descriptor,
        new java.lang.String[] { "LocalesInfo", "DefaultLocaleInfo", "DefaultTimeZone", "DefaultLocaleInfo", "DefaultTimeZone", });
    internal_static_com_tiwari_studence_proto_locale_LocaleInfoPb_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_tiwari_studence_proto_locale_LocaleInfoPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tiwari_studence_proto_locale_LocaleInfoPb_descriptor,
        new java.lang.String[] { "Locale", "Locale", });
    internal_static_com_tiwari_studence_proto_locale_LocaleInfoUiPb_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_tiwari_studence_proto_locale_LocaleInfoUiPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tiwari_studence_proto_locale_LocaleInfoUiPb_descriptor,
        new java.lang.String[] { "Locale", "Locale", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.tiwari.studence.proto.mergeOption.MergeOption.mergeToken);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.tiwari.studence.proto.time.TimePbOuterClass.getDescriptor();
    com.tiwari.studence.proto.mergeOption.MergeOption.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
