// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: searchdynamodb.proto

package com.tiwari.studence.proto.search;

public interface DynamoDbSearchPbOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.tiwari.studence.proto.search.DynamoDbSearchPb)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.tiwari.studence.proto.search.DynamoDBSearchMode mode = 1;</code>
   * @return The enum numeric value on the wire for mode.
   */
  int getModeValue();
  /**
   * <code>.com.tiwari.studence.proto.search.DynamoDBSearchMode mode = 1;</code>
   * @return The mode.
   */
  com.tiwari.studence.proto.search.DynamoDBSearchMode getMode();

  /**
   * <code>string tableName = 2;</code>
   * @return The tableName.
   */
  java.lang.String getTableName();
  /**
   * <code>string tableName = 2;</code>
   * @return The bytes for tableName.
   */
  com.google.protobuf.ByteString
      getTableNameBytes();

  /**
   * <code>string indexName = 3;</code>
   * @return The indexName.
   */
  java.lang.String getIndexName();
  /**
   * <code>string indexName = 3;</code>
   * @return The bytes for indexName.
   */
  com.google.protobuf.ByteString
      getIndexNameBytes();

  /**
   * <code>string keyConditionExpression = 4;</code>
   * @return The keyConditionExpression.
   */
  java.lang.String getKeyConditionExpression();
  /**
   * <code>string keyConditionExpression = 4;</code>
   * @return The bytes for keyConditionExpression.
   */
  com.google.protobuf.ByteString
      getKeyConditionExpressionBytes();

  /**
   * <code>string filterExpression = 6;</code>
   * @return The filterExpression.
   */
  java.lang.String getFilterExpression();
  /**
   * <code>string filterExpression = 6;</code>
   * @return The bytes for filterExpression.
   */
  com.google.protobuf.ByteString
      getFilterExpressionBytes();

  /**
   * <code>repeated .com.tiwari.studence.proto.search.AttributeNameValuePair expressionAttribute = 7;</code>
   */
  java.util.List<com.tiwari.studence.proto.search.AttributeNameValuePair> 
      getExpressionAttributeList();
  /**
   * <code>repeated .com.tiwari.studence.proto.search.AttributeNameValuePair expressionAttribute = 7;</code>
   */
  com.tiwari.studence.proto.search.AttributeNameValuePair getExpressionAttribute(int index);
  /**
   * <code>repeated .com.tiwari.studence.proto.search.AttributeNameValuePair expressionAttribute = 7;</code>
   */
  int getExpressionAttributeCount();
  /**
   * <code>repeated .com.tiwari.studence.proto.search.AttributeNameValuePair expressionAttribute = 7;</code>
   */
  java.util.List<? extends com.tiwari.studence.proto.search.AttributeNameValuePairOrBuilder> 
      getExpressionAttributeOrBuilderList();
  /**
   * <code>repeated .com.tiwari.studence.proto.search.AttributeNameValuePair expressionAttribute = 7;</code>
   */
  com.tiwari.studence.proto.search.AttributeNameValuePairOrBuilder getExpressionAttributeOrBuilder(
      int index);
}
