// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: searchdynamodb.proto

package com.tiwari.studence.proto.search;

public final class Searchdynamodb {
  private Searchdynamodb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tiwari_studence_proto_search_AttributeNameValuePair_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tiwari_studence_proto_search_AttributeNameValuePair_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tiwari_studence_proto_search_SearchPb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tiwari_studence_proto_search_SearchPb_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024searchdynamodb.proto\022 com.tiwari.stude" +
      "nce.proto.search\"\356\001\n\026AttributeNameValueP" +
      "air\022=\n\004type\030\001 \001(\0162/.com.tiwari.studence." +
      "proto.search.DynamoDBValue\022\014\n\004name\030\002 \001(\t" +
      "\022\020\n\010intValue\030\003 \001(\005\022\022\n\nfloatValue\030\004 \001(\002\022\023" +
      "\n\013stringValue\030\005 \001(\t\022\023\n\013binaryValue\030\006 \001(\014" +
      "\022\032\n\022attributeNameAlias\030\007 \001(\t\022\033\n\023attribut" +
      "eValueAlias\030\010 \001(\t\"\305\002\n\010SearchPb\022F\n\004type\030\001" +
      " \001(\01628.com.tiwari.studence.proto.search." +
      "ComparisonOperatorEnum\022P\n\016attributeFirst" +
      "\030\002 \001(\01328.com.tiwari.studence.proto.searc" +
      "h.AttributeNameValuePair\022Q\n\017attributeSec" +
      "ond\030\003 \001(\01328.com.tiwari.studence.proto.se" +
      "arch.AttributeNameValuePair\022L\n\nattribute" +
      "s\030\004 \003(\01328.com.tiwari.studence.proto.sear" +
      "ch.AttributeNameValuePair*\375\001\n\026Comparison" +
      "OperatorEnum\022\013\n\007UNKNOWN\020\000\022\014\n\010EQUAL_TO\020\001\022" +
      "\020\n\014NOT_EQUAL_TO\020\002\022\020\n\014GREATER_THAN\020\003\022\r\n\tL" +
      "ESS_THAN\020\004\022\034\n\030GREATER_THAN_OR_EQUAL_TO\020\005" +
      "\022\031\n\025LESS_THAN_OR_EQUAL_TO\020\006\022\013\n\007BETWEEN\020\007" +
      "\022\006\n\002IN\020\010\022\014\n\010NOT_NULL\020\t\022\010\n\004NULL\020\n\022\014\n\010CONT" +
      "AINS\020\013\022\020\n\014NOT_CONTAINS\020\014\022\017\n\013BEGINS_WITH\020" +
      "\r*\227\001\n\rDynamoDBValue\022\036\n\032DYNAMODB_VALUE_UN" +
      "SPECIFIED\020\000\022\031\n\025DYNAMODB_VALUE_STRING\020\001\022\026" +
      "\n\022DYNAMODB_VALUE_INT\020\002\022\031\n\025DYNAMODB_VALUE" +
      "_BINARY\020\003\022\030\n\024DYNAMODB_VALUE_FLOAT\020\004B\005P\001\240" +
      "\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_tiwari_studence_proto_search_AttributeNameValuePair_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_tiwari_studence_proto_search_AttributeNameValuePair_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tiwari_studence_proto_search_AttributeNameValuePair_descriptor,
        new java.lang.String[] { "Type", "Name", "IntValue", "FloatValue", "StringValue", "BinaryValue", "AttributeNameAlias", "AttributeValueAlias", });
    internal_static_com_tiwari_studence_proto_search_SearchPb_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_tiwari_studence_proto_search_SearchPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tiwari_studence_proto_search_SearchPb_descriptor,
        new java.lang.String[] { "Type", "AttributeFirst", "AttributeSecond", "Attributes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
