// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stringParserConfig.proto

package com.tiwari.studence.proto.stringParser;

/**
 * Protobuf type {@code com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb}
 */
public final class CaseNormalizerUiPb extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb)
    CaseNormalizerUiPbOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CaseNormalizerUiPb.newBuilder() to construct.
  private CaseNormalizerUiPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CaseNormalizerUiPb() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CaseNormalizerUiPb();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tiwari.studence.proto.stringParser.StringParserConfig.internal_static_com_tiwari_studence_proto_stringParser_CaseNormalizerUiPb_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tiwari.studence.proto.stringParser.StringParserConfig.internal_static_com_tiwari_studence_proto_stringParser_CaseNormalizerUiPb_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb.class, com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb.Builder.class);
  }

  private int bitField0_;
  public static final int ISENABLED_FIELD_NUMBER = 1;
  private boolean isEnabled_ = false;
  /**
   * <code>optional bool isEnabled = 1;</code>
   * @return Whether the isEnabled field is set.
   */
  @java.lang.Override
  public boolean hasIsEnabled() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional bool isEnabled = 1;</code>
   * @return The isEnabled.
   */
  @java.lang.Override
  public boolean getIsEnabled() {
    return isEnabled_;
  }

  public static final int TOUPPERCASE_FIELD_NUMBER = 2;
  private boolean toUppercase_ = false;
  /**
   * <code>optional bool toUppercase = 2;</code>
   * @return Whether the toUppercase field is set.
   */
  @java.lang.Override
  public boolean hasToUppercase() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional bool toUppercase = 2;</code>
   * @return The toUppercase.
   */
  @java.lang.Override
  public boolean getToUppercase() {
    return toUppercase_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeBool(1, isEnabled_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeBool(2, toUppercase_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, isEnabled_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, toUppercase_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb)) {
      return super.equals(obj);
    }
    com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb other = (com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb) obj;

    if (hasIsEnabled() != other.hasIsEnabled()) return false;
    if (hasIsEnabled()) {
      if (getIsEnabled()
          != other.getIsEnabled()) return false;
    }
    if (hasToUppercase() != other.hasToUppercase()) return false;
    if (hasToUppercase()) {
      if (getToUppercase()
          != other.getToUppercase()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasIsEnabled()) {
      hash = (37 * hash) + ISENABLED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsEnabled());
    }
    if (hasToUppercase()) {
      hash = (37 * hash) + TOUPPERCASE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getToUppercase());
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb)
      com.tiwari.studence.proto.stringParser.CaseNormalizerUiPbOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tiwari.studence.proto.stringParser.StringParserConfig.internal_static_com_tiwari_studence_proto_stringParser_CaseNormalizerUiPb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tiwari.studence.proto.stringParser.StringParserConfig.internal_static_com_tiwari_studence_proto_stringParser_CaseNormalizerUiPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb.class, com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb.Builder.class);
    }

    // Construct using com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      isEnabled_ = false;
      toUppercase_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tiwari.studence.proto.stringParser.StringParserConfig.internal_static_com_tiwari_studence_proto_stringParser_CaseNormalizerUiPb_descriptor;
    }

    @java.lang.Override
    public com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb getDefaultInstanceForType() {
      return com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb.getDefaultInstance();
    }

    @java.lang.Override
    public com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb build() {
      com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb buildPartial() {
      com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb result = new com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.isEnabled_ = isEnabled_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.toUppercase_ = toUppercase_;
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb) {
        return mergeFrom((com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb other) {
      if (other == com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb.getDefaultInstance()) return this;
      if (other.hasIsEnabled()) {
        setIsEnabled(other.getIsEnabled());
      }
      if (other.hasToUppercase()) {
        setToUppercase(other.getToUppercase());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              isEnabled_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              toUppercase_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean isEnabled_ ;
    /**
     * <code>optional bool isEnabled = 1;</code>
     * @return Whether the isEnabled field is set.
     */
    @java.lang.Override
    public boolean hasIsEnabled() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bool isEnabled = 1;</code>
     * @return The isEnabled.
     */
    @java.lang.Override
    public boolean getIsEnabled() {
      return isEnabled_;
    }
    /**
     * <code>optional bool isEnabled = 1;</code>
     * @param value The isEnabled to set.
     * @return This builder for chaining.
     */
    public Builder setIsEnabled(boolean value) {
      
      isEnabled_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool isEnabled = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsEnabled() {
      bitField0_ = (bitField0_ & ~0x00000001);
      isEnabled_ = false;
      onChanged();
      return this;
    }

    private boolean toUppercase_ ;
    /**
     * <code>optional bool toUppercase = 2;</code>
     * @return Whether the toUppercase field is set.
     */
    @java.lang.Override
    public boolean hasToUppercase() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional bool toUppercase = 2;</code>
     * @return The toUppercase.
     */
    @java.lang.Override
    public boolean getToUppercase() {
      return toUppercase_;
    }
    /**
     * <code>optional bool toUppercase = 2;</code>
     * @param value The toUppercase to set.
     * @return This builder for chaining.
     */
    public Builder setToUppercase(boolean value) {
      
      toUppercase_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool toUppercase = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearToUppercase() {
      bitField0_ = (bitField0_ & ~0x00000002);
      toUppercase_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb)
  }

  // @@protoc_insertion_point(class_scope:com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb)
  private static final com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb();
  }

  public static com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CaseNormalizerUiPb>
      PARSER = new com.google.protobuf.AbstractParser<CaseNormalizerUiPb>() {
    @java.lang.Override
    public CaseNormalizerUiPb parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CaseNormalizerUiPb> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CaseNormalizerUiPb> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tiwari.studence.proto.stringParser.CaseNormalizerUiPb getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

