// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: index.proto

package com.tiwari.studence.proto.index;

public interface ListIndicesResponsePbOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.tiwari.studence.proto.index.ListIndicesResponsePb)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.tiwari.studence.proto.index.IndexPb indices = 1;</code>
   */
  java.util.List<com.tiwari.studence.proto.index.IndexPb> 
      getIndicesList();
  /**
   * <code>repeated .com.tiwari.studence.proto.index.IndexPb indices = 1;</code>
   */
  com.tiwari.studence.proto.index.IndexPb getIndices(int index);
  /**
   * <code>repeated .com.tiwari.studence.proto.index.IndexPb indices = 1;</code>
   */
  int getIndicesCount();
  /**
   * <code>repeated .com.tiwari.studence.proto.index.IndexPb indices = 1;</code>
   */
  java.util.List<? extends com.tiwari.studence.proto.index.IndexPbOrBuilder> 
      getIndicesOrBuilderList();
  /**
   * <code>repeated .com.tiwari.studence.proto.index.IndexPb indices = 1;</code>
   */
  com.tiwari.studence.proto.index.IndexPbOrBuilder getIndicesOrBuilder(
      int index);
}
