// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: htmlWidgets.proto

package com.tiwari.studence.proto.htmlWidgets;

public interface BorderConfigPbOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.tiwari.studence.proto.htmlWidgets.BorderConfigPb)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.ValueTypeEnum borderValueType = 1;</code>
   * @return The enum numeric value on the wire for borderValueType.
   */
  int getBorderValueTypeValue();
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.ValueTypeEnum borderValueType = 1;</code>
   * @return The borderValueType.
   */
  com.tiwari.studence.proto.htmlWidgets.ValueTypeEnum getBorderValueType();

  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.ValueUnitTypeEnum unit = 2;</code>
   * @return The enum numeric value on the wire for unit.
   */
  int getUnitValue();
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.ValueUnitTypeEnum unit = 2;</code>
   * @return The unit.
   */
  com.tiwari.studence.proto.htmlWidgets.ValueUnitTypeEnum getUnit();

  /**
   * <code>double value = 3;</code>
   * @return The value.
   */
  double getValue();

  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.DirectionConfig multipleValues = 4;</code>
   * @return Whether the multipleValues field is set.
   */
  boolean hasMultipleValues();
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.DirectionConfig multipleValues = 4;</code>
   * @return The multipleValues.
   */
  com.tiwari.studence.proto.htmlWidgets.DirectionConfig getMultipleValues();
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.DirectionConfig multipleValues = 4;</code>
   */
  com.tiwari.studence.proto.htmlWidgets.DirectionConfigOrBuilder getMultipleValuesOrBuilder();

  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.ColorPb color = 5;</code>
   * @return Whether the color field is set.
   */
  boolean hasColor();
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.ColorPb color = 5;</code>
   * @return The color.
   */
  com.tiwari.studence.proto.htmlWidgets.ColorPb getColor();
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.ColorPb color = 5;</code>
   */
  com.tiwari.studence.proto.htmlWidgets.ColorPbOrBuilder getColorOrBuilder();

  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.BorderTypeEnum borderType = 6;</code>
   * @return The enum numeric value on the wire for borderType.
   */
  int getBorderTypeValue();
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.BorderTypeEnum borderType = 6;</code>
   * @return The borderType.
   */
  com.tiwari.studence.proto.htmlWidgets.BorderTypeEnum getBorderType();
}
