// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: htmlWidgets.proto

package com.tiwari.studence.proto.htmlWidgets;

public interface ButtonEventPbOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.tiwari.studence.proto.htmlWidgets.ButtonEventPb)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.ColorPb backgroundColor = 1;</code>
   * @return Whether the backgroundColor field is set.
   */
  boolean hasBackgroundColor();
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.ColorPb backgroundColor = 1;</code>
   * @return The backgroundColor.
   */
  com.tiwari.studence.proto.htmlWidgets.ColorPb getBackgroundColor();
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.ColorPb backgroundColor = 1;</code>
   */
  com.tiwari.studence.proto.htmlWidgets.ColorPbOrBuilder getBackgroundColorOrBuilder();

  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.ColorPb textColor = 2;</code>
   * @return Whether the textColor field is set.
   */
  boolean hasTextColor();
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.ColorPb textColor = 2;</code>
   * @return The textColor.
   */
  com.tiwari.studence.proto.htmlWidgets.ColorPb getTextColor();
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.ColorPb textColor = 2;</code>
   */
  com.tiwari.studence.proto.htmlWidgets.ColorPbOrBuilder getTextColorOrBuilder();

  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.HeightPb height = 3;</code>
   * @return Whether the height field is set.
   */
  boolean hasHeight();
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.HeightPb height = 3;</code>
   * @return The height.
   */
  com.tiwari.studence.proto.htmlWidgets.HeightPb getHeight();
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.HeightPb height = 3;</code>
   */
  com.tiwari.studence.proto.htmlWidgets.HeightPbOrBuilder getHeightOrBuilder();

  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.WidthPb width = 4;</code>
   * @return Whether the width field is set.
   */
  boolean hasWidth();
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.WidthPb width = 4;</code>
   * @return The width.
   */
  com.tiwari.studence.proto.htmlWidgets.WidthPb getWidth();
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.WidthPb width = 4;</code>
   */
  com.tiwari.studence.proto.htmlWidgets.WidthPbOrBuilder getWidthOrBuilder();

  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.BorderConfigPb border = 5;</code>
   * @return Whether the border field is set.
   */
  boolean hasBorder();
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.BorderConfigPb border = 5;</code>
   * @return The border.
   */
  com.tiwari.studence.proto.htmlWidgets.BorderConfigPb getBorder();
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.BorderConfigPb border = 5;</code>
   */
  com.tiwari.studence.proto.htmlWidgets.BorderConfigPbOrBuilder getBorderOrBuilder();

  /**
   * <code>string label = 6;</code>
   * @return The label.
   */
  java.lang.String getLabel();
  /**
   * <code>string label = 6;</code>
   * @return The bytes for label.
   */
  com.google.protobuf.ByteString
      getLabelBytes();

  /**
   * <code>string loadingText = 7;</code>
   * @return The loadingText.
   */
  java.lang.String getLoadingText();
  /**
   * <code>string loadingText = 7;</code>
   * @return The bytes for loadingText.
   */
  com.google.protobuf.ByteString
      getLoadingTextBytes();

  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.ColorPb foregroundColor = 8;</code>
   * @return Whether the foregroundColor field is set.
   */
  boolean hasForegroundColor();
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.ColorPb foregroundColor = 8;</code>
   * @return The foregroundColor.
   */
  com.tiwari.studence.proto.htmlWidgets.ColorPb getForegroundColor();
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.ColorPb foregroundColor = 8;</code>
   */
  com.tiwari.studence.proto.htmlWidgets.ColorPbOrBuilder getForegroundColorOrBuilder();
}
