// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: htmlWidgets.proto

package com.tiwari.studence.proto.htmlWidgets;

/**
 * Protobuf type {@code com.tiwari.studence.proto.htmlWidgets.CheckboxPb}
 */
public final class CheckboxPb extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.tiwari.studence.proto.htmlWidgets.CheckboxPb)
    CheckboxPbOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CheckboxPb.newBuilder() to construct.
  private CheckboxPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CheckboxPb() {
    isChecked_ = 0;
    checkboxName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CheckboxPb();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tiwari.studence.proto.htmlWidgets.HtmlWidgets.internal_static_com_tiwari_studence_proto_htmlWidgets_CheckboxPb_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tiwari.studence.proto.htmlWidgets.HtmlWidgets.internal_static_com_tiwari_studence_proto_htmlWidgets_CheckboxPb_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tiwari.studence.proto.htmlWidgets.CheckboxPb.class, com.tiwari.studence.proto.htmlWidgets.CheckboxPb.Builder.class);
  }

  public static final int ISCHECKED_FIELD_NUMBER = 1;
  private int isChecked_ = 0;
  /**
   * <code>.com.tiwari.studence.proto.datatypes.BooleanEnum isChecked = 1;</code>
   * @return The enum numeric value on the wire for isChecked.
   */
  @java.lang.Override public int getIsCheckedValue() {
    return isChecked_;
  }
  /**
   * <code>.com.tiwari.studence.proto.datatypes.BooleanEnum isChecked = 1;</code>
   * @return The isChecked.
   */
  @java.lang.Override public com.tiwari.studence.proto.datatypes.BooleanEnum getIsChecked() {
    com.tiwari.studence.proto.datatypes.BooleanEnum result = com.tiwari.studence.proto.datatypes.BooleanEnum.forNumber(isChecked_);
    return result == null ? com.tiwari.studence.proto.datatypes.BooleanEnum.UNRECOGNIZED : result;
  }

  public static final int CHECKBOXNAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object checkboxName_ = "";
  /**
   * <code>string checkboxName = 2;</code>
   * @return The checkboxName.
   */
  @java.lang.Override
  public java.lang.String getCheckboxName() {
    java.lang.Object ref = checkboxName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      checkboxName_ = s;
      return s;
    }
  }
  /**
   * <code>string checkboxName = 2;</code>
   * @return The bytes for checkboxName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCheckboxNameBytes() {
    java.lang.Object ref = checkboxName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      checkboxName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (isChecked_ != com.tiwari.studence.proto.datatypes.BooleanEnum.UNKNOWN_BOOLEAN_TYPE.getNumber()) {
      output.writeEnum(1, isChecked_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(checkboxName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, checkboxName_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (isChecked_ != com.tiwari.studence.proto.datatypes.BooleanEnum.UNKNOWN_BOOLEAN_TYPE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, isChecked_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(checkboxName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, checkboxName_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tiwari.studence.proto.htmlWidgets.CheckboxPb)) {
      return super.equals(obj);
    }
    com.tiwari.studence.proto.htmlWidgets.CheckboxPb other = (com.tiwari.studence.proto.htmlWidgets.CheckboxPb) obj;

    if (isChecked_ != other.isChecked_) return false;
    if (!getCheckboxName()
        .equals(other.getCheckboxName())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ISCHECKED_FIELD_NUMBER;
    hash = (53 * hash) + isChecked_;
    hash = (37 * hash) + CHECKBOXNAME_FIELD_NUMBER;
    hash = (53 * hash) + getCheckboxName().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tiwari.studence.proto.htmlWidgets.CheckboxPb parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tiwari.studence.proto.htmlWidgets.CheckboxPb parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tiwari.studence.proto.htmlWidgets.CheckboxPb parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tiwari.studence.proto.htmlWidgets.CheckboxPb parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tiwari.studence.proto.htmlWidgets.CheckboxPb parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tiwari.studence.proto.htmlWidgets.CheckboxPb parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tiwari.studence.proto.htmlWidgets.CheckboxPb parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tiwari.studence.proto.htmlWidgets.CheckboxPb parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tiwari.studence.proto.htmlWidgets.CheckboxPb parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tiwari.studence.proto.htmlWidgets.CheckboxPb parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tiwari.studence.proto.htmlWidgets.CheckboxPb parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tiwari.studence.proto.htmlWidgets.CheckboxPb parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tiwari.studence.proto.htmlWidgets.CheckboxPb prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.tiwari.studence.proto.htmlWidgets.CheckboxPb}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.tiwari.studence.proto.htmlWidgets.CheckboxPb)
      com.tiwari.studence.proto.htmlWidgets.CheckboxPbOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tiwari.studence.proto.htmlWidgets.HtmlWidgets.internal_static_com_tiwari_studence_proto_htmlWidgets_CheckboxPb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tiwari.studence.proto.htmlWidgets.HtmlWidgets.internal_static_com_tiwari_studence_proto_htmlWidgets_CheckboxPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tiwari.studence.proto.htmlWidgets.CheckboxPb.class, com.tiwari.studence.proto.htmlWidgets.CheckboxPb.Builder.class);
    }

    // Construct using com.tiwari.studence.proto.htmlWidgets.CheckboxPb.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      isChecked_ = 0;
      checkboxName_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tiwari.studence.proto.htmlWidgets.HtmlWidgets.internal_static_com_tiwari_studence_proto_htmlWidgets_CheckboxPb_descriptor;
    }

    @java.lang.Override
    public com.tiwari.studence.proto.htmlWidgets.CheckboxPb getDefaultInstanceForType() {
      return com.tiwari.studence.proto.htmlWidgets.CheckboxPb.getDefaultInstance();
    }

    @java.lang.Override
    public com.tiwari.studence.proto.htmlWidgets.CheckboxPb build() {
      com.tiwari.studence.proto.htmlWidgets.CheckboxPb result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tiwari.studence.proto.htmlWidgets.CheckboxPb buildPartial() {
      com.tiwari.studence.proto.htmlWidgets.CheckboxPb result = new com.tiwari.studence.proto.htmlWidgets.CheckboxPb(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.tiwari.studence.proto.htmlWidgets.CheckboxPb result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.isChecked_ = isChecked_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.checkboxName_ = checkboxName_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tiwari.studence.proto.htmlWidgets.CheckboxPb) {
        return mergeFrom((com.tiwari.studence.proto.htmlWidgets.CheckboxPb)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tiwari.studence.proto.htmlWidgets.CheckboxPb other) {
      if (other == com.tiwari.studence.proto.htmlWidgets.CheckboxPb.getDefaultInstance()) return this;
      if (other.isChecked_ != 0) {
        setIsCheckedValue(other.getIsCheckedValue());
      }
      if (!other.getCheckboxName().isEmpty()) {
        checkboxName_ = other.checkboxName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              isChecked_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              checkboxName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int isChecked_ = 0;
    /**
     * <code>.com.tiwari.studence.proto.datatypes.BooleanEnum isChecked = 1;</code>
     * @return The enum numeric value on the wire for isChecked.
     */
    @java.lang.Override public int getIsCheckedValue() {
      return isChecked_;
    }
    /**
     * <code>.com.tiwari.studence.proto.datatypes.BooleanEnum isChecked = 1;</code>
     * @param value The enum numeric value on the wire for isChecked to set.
     * @return This builder for chaining.
     */
    public Builder setIsCheckedValue(int value) {
      isChecked_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.tiwari.studence.proto.datatypes.BooleanEnum isChecked = 1;</code>
     * @return The isChecked.
     */
    @java.lang.Override
    public com.tiwari.studence.proto.datatypes.BooleanEnum getIsChecked() {
      com.tiwari.studence.proto.datatypes.BooleanEnum result = com.tiwari.studence.proto.datatypes.BooleanEnum.forNumber(isChecked_);
      return result == null ? com.tiwari.studence.proto.datatypes.BooleanEnum.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.tiwari.studence.proto.datatypes.BooleanEnum isChecked = 1;</code>
     * @param value The isChecked to set.
     * @return This builder for chaining.
     */
    public Builder setIsChecked(com.tiwari.studence.proto.datatypes.BooleanEnum value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      isChecked_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.tiwari.studence.proto.datatypes.BooleanEnum isChecked = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsChecked() {
      bitField0_ = (bitField0_ & ~0x00000001);
      isChecked_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object checkboxName_ = "";
    /**
     * <code>string checkboxName = 2;</code>
     * @return The checkboxName.
     */
    public java.lang.String getCheckboxName() {
      java.lang.Object ref = checkboxName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        checkboxName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string checkboxName = 2;</code>
     * @return The bytes for checkboxName.
     */
    public com.google.protobuf.ByteString
        getCheckboxNameBytes() {
      java.lang.Object ref = checkboxName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        checkboxName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string checkboxName = 2;</code>
     * @param value The checkboxName to set.
     * @return This builder for chaining.
     */
    public Builder setCheckboxName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      checkboxName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string checkboxName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCheckboxName() {
      checkboxName_ = getDefaultInstance().getCheckboxName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string checkboxName = 2;</code>
     * @param value The bytes for checkboxName to set.
     * @return This builder for chaining.
     */
    public Builder setCheckboxNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      checkboxName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.tiwari.studence.proto.htmlWidgets.CheckboxPb)
  }

  // @@protoc_insertion_point(class_scope:com.tiwari.studence.proto.htmlWidgets.CheckboxPb)
  private static final com.tiwari.studence.proto.htmlWidgets.CheckboxPb DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tiwari.studence.proto.htmlWidgets.CheckboxPb();
  }

  public static com.tiwari.studence.proto.htmlWidgets.CheckboxPb getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CheckboxPb>
      PARSER = new com.google.protobuf.AbstractParser<CheckboxPb>() {
    @java.lang.Override
    public CheckboxPb parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CheckboxPb> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CheckboxPb> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tiwari.studence.proto.htmlWidgets.CheckboxPb getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

