// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: htmlWidgets.proto

package com.tiwari.studence.proto.htmlWidgets;

/**
 * Protobuf type {@code com.tiwari.studence.proto.htmlWidgets.ColorPb}
 */
public final class ColorPb extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.tiwari.studence.proto.htmlWidgets.ColorPb)
    ColorPbOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ColorPb.newBuilder() to construct.
  private ColorPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ColorPb() {
    colorType_ = 0;
    colorInType_ = 0;
    hexCodeBackgroundColor_ = "";
    hexCodefontColor_ = "";
    hexCodeForegroundColor_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ColorPb();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tiwari.studence.proto.htmlWidgets.HtmlWidgets.internal_static_com_tiwari_studence_proto_htmlWidgets_ColorPb_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tiwari.studence.proto.htmlWidgets.HtmlWidgets.internal_static_com_tiwari_studence_proto_htmlWidgets_ColorPb_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tiwari.studence.proto.htmlWidgets.ColorPb.class, com.tiwari.studence.proto.htmlWidgets.ColorPb.Builder.class);
  }

  public static final int COLORTYPE_FIELD_NUMBER = 1;
  private int colorType_ = 0;
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.ColorTypeEnum colorType = 1;</code>
   * @return The enum numeric value on the wire for colorType.
   */
  @java.lang.Override public int getColorTypeValue() {
    return colorType_;
  }
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.ColorTypeEnum colorType = 1;</code>
   * @return The colorType.
   */
  @java.lang.Override public com.tiwari.studence.proto.htmlWidgets.ColorTypeEnum getColorType() {
    com.tiwari.studence.proto.htmlWidgets.ColorTypeEnum result = com.tiwari.studence.proto.htmlWidgets.ColorTypeEnum.forNumber(colorType_);
    return result == null ? com.tiwari.studence.proto.htmlWidgets.ColorTypeEnum.UNRECOGNIZED : result;
  }

  public static final int COLORINTYPE_FIELD_NUMBER = 2;
  private int colorInType_ = 0;
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.ColorInTypeEnum colorInType = 2;</code>
   * @return The enum numeric value on the wire for colorInType.
   */
  @java.lang.Override public int getColorInTypeValue() {
    return colorInType_;
  }
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.ColorInTypeEnum colorInType = 2;</code>
   * @return The colorInType.
   */
  @java.lang.Override public com.tiwari.studence.proto.htmlWidgets.ColorInTypeEnum getColorInType() {
    com.tiwari.studence.proto.htmlWidgets.ColorInTypeEnum result = com.tiwari.studence.proto.htmlWidgets.ColorInTypeEnum.forNumber(colorInType_);
    return result == null ? com.tiwari.studence.proto.htmlWidgets.ColorInTypeEnum.UNRECOGNIZED : result;
  }

  public static final int RGBOBACKGROUNDCOLOR_FIELD_NUMBER = 3;
  private com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboBackgroundColor_;
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboBackgroundColor = 3;</code>
   * @return Whether the rgboBackgroundColor field is set.
   */
  @java.lang.Override
  public boolean hasRgboBackgroundColor() {
    return rgboBackgroundColor_ != null;
  }
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboBackgroundColor = 3;</code>
   * @return The rgboBackgroundColor.
   */
  @java.lang.Override
  public com.tiwari.studence.proto.htmlWidgets.RGBOPb getRgboBackgroundColor() {
    return rgboBackgroundColor_ == null ? com.tiwari.studence.proto.htmlWidgets.RGBOPb.getDefaultInstance() : rgboBackgroundColor_;
  }
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboBackgroundColor = 3;</code>
   */
  @java.lang.Override
  public com.tiwari.studence.proto.htmlWidgets.RGBOPbOrBuilder getRgboBackgroundColorOrBuilder() {
    return rgboBackgroundColor_ == null ? com.tiwari.studence.proto.htmlWidgets.RGBOPb.getDefaultInstance() : rgboBackgroundColor_;
  }

  public static final int ARGBBACKGROUNDCOLOR_FIELD_NUMBER = 4;
  private com.tiwari.studence.proto.htmlWidgets.ARGBPb argbBackgroundColor_;
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.ARGBPb argbBackgroundColor = 4;</code>
   * @return Whether the argbBackgroundColor field is set.
   */
  @java.lang.Override
  public boolean hasArgbBackgroundColor() {
    return argbBackgroundColor_ != null;
  }
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.ARGBPb argbBackgroundColor = 4;</code>
   * @return The argbBackgroundColor.
   */
  @java.lang.Override
  public com.tiwari.studence.proto.htmlWidgets.ARGBPb getArgbBackgroundColor() {
    return argbBackgroundColor_ == null ? com.tiwari.studence.proto.htmlWidgets.ARGBPb.getDefaultInstance() : argbBackgroundColor_;
  }
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.ARGBPb argbBackgroundColor = 4;</code>
   */
  @java.lang.Override
  public com.tiwari.studence.proto.htmlWidgets.ARGBPbOrBuilder getArgbBackgroundColorOrBuilder() {
    return argbBackgroundColor_ == null ? com.tiwari.studence.proto.htmlWidgets.ARGBPb.getDefaultInstance() : argbBackgroundColor_;
  }

  public static final int HEXCODEBACKGROUNDCOLOR_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object hexCodeBackgroundColor_ = "";
  /**
   * <code>string hexCodeBackgroundColor = 5;</code>
   * @return The hexCodeBackgroundColor.
   */
  @java.lang.Override
  public java.lang.String getHexCodeBackgroundColor() {
    java.lang.Object ref = hexCodeBackgroundColor_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      hexCodeBackgroundColor_ = s;
      return s;
    }
  }
  /**
   * <code>string hexCodeBackgroundColor = 5;</code>
   * @return The bytes for hexCodeBackgroundColor.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHexCodeBackgroundColorBytes() {
    java.lang.Object ref = hexCodeBackgroundColor_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      hexCodeBackgroundColor_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RGBOFONTCOLOR_FIELD_NUMBER = 6;
  private com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboFontColor_;
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboFontColor = 6;</code>
   * @return Whether the rgboFontColor field is set.
   */
  @java.lang.Override
  public boolean hasRgboFontColor() {
    return rgboFontColor_ != null;
  }
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboFontColor = 6;</code>
   * @return The rgboFontColor.
   */
  @java.lang.Override
  public com.tiwari.studence.proto.htmlWidgets.RGBOPb getRgboFontColor() {
    return rgboFontColor_ == null ? com.tiwari.studence.proto.htmlWidgets.RGBOPb.getDefaultInstance() : rgboFontColor_;
  }
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboFontColor = 6;</code>
   */
  @java.lang.Override
  public com.tiwari.studence.proto.htmlWidgets.RGBOPbOrBuilder getRgboFontColorOrBuilder() {
    return rgboFontColor_ == null ? com.tiwari.studence.proto.htmlWidgets.RGBOPb.getDefaultInstance() : rgboFontColor_;
  }

  public static final int AEGBFONTCOLOR_FIELD_NUMBER = 7;
  private com.tiwari.studence.proto.htmlWidgets.ARGBPb aegbFontColor_;
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.ARGBPb aegbFontColor = 7;</code>
   * @return Whether the aegbFontColor field is set.
   */
  @java.lang.Override
  public boolean hasAegbFontColor() {
    return aegbFontColor_ != null;
  }
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.ARGBPb aegbFontColor = 7;</code>
   * @return The aegbFontColor.
   */
  @java.lang.Override
  public com.tiwari.studence.proto.htmlWidgets.ARGBPb getAegbFontColor() {
    return aegbFontColor_ == null ? com.tiwari.studence.proto.htmlWidgets.ARGBPb.getDefaultInstance() : aegbFontColor_;
  }
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.ARGBPb aegbFontColor = 7;</code>
   */
  @java.lang.Override
  public com.tiwari.studence.proto.htmlWidgets.ARGBPbOrBuilder getAegbFontColorOrBuilder() {
    return aegbFontColor_ == null ? com.tiwari.studence.proto.htmlWidgets.ARGBPb.getDefaultInstance() : aegbFontColor_;
  }

  public static final int HEXCODEFONTCOLOR_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object hexCodefontColor_ = "";
  /**
   * <code>string hexCodefontColor = 8;</code>
   * @return The hexCodefontColor.
   */
  @java.lang.Override
  public java.lang.String getHexCodefontColor() {
    java.lang.Object ref = hexCodefontColor_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      hexCodefontColor_ = s;
      return s;
    }
  }
  /**
   * <code>string hexCodefontColor = 8;</code>
   * @return The bytes for hexCodefontColor.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHexCodefontColorBytes() {
    java.lang.Object ref = hexCodefontColor_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      hexCodefontColor_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RGBOFOREGROUNDCOLOR_FIELD_NUMBER = 9;
  private com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboForegroundColor_;
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboForegroundColor = 9;</code>
   * @return Whether the rgboForegroundColor field is set.
   */
  @java.lang.Override
  public boolean hasRgboForegroundColor() {
    return rgboForegroundColor_ != null;
  }
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboForegroundColor = 9;</code>
   * @return The rgboForegroundColor.
   */
  @java.lang.Override
  public com.tiwari.studence.proto.htmlWidgets.RGBOPb getRgboForegroundColor() {
    return rgboForegroundColor_ == null ? com.tiwari.studence.proto.htmlWidgets.RGBOPb.getDefaultInstance() : rgboForegroundColor_;
  }
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboForegroundColor = 9;</code>
   */
  @java.lang.Override
  public com.tiwari.studence.proto.htmlWidgets.RGBOPbOrBuilder getRgboForegroundColorOrBuilder() {
    return rgboForegroundColor_ == null ? com.tiwari.studence.proto.htmlWidgets.RGBOPb.getDefaultInstance() : rgboForegroundColor_;
  }

  public static final int AEGBFOREGROUNDCOLOR_FIELD_NUMBER = 10;
  private com.tiwari.studence.proto.htmlWidgets.ARGBPb aegbForegroundColor_;
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.ARGBPb aegbForegroundColor = 10;</code>
   * @return Whether the aegbForegroundColor field is set.
   */
  @java.lang.Override
  public boolean hasAegbForegroundColor() {
    return aegbForegroundColor_ != null;
  }
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.ARGBPb aegbForegroundColor = 10;</code>
   * @return The aegbForegroundColor.
   */
  @java.lang.Override
  public com.tiwari.studence.proto.htmlWidgets.ARGBPb getAegbForegroundColor() {
    return aegbForegroundColor_ == null ? com.tiwari.studence.proto.htmlWidgets.ARGBPb.getDefaultInstance() : aegbForegroundColor_;
  }
  /**
   * <code>.com.tiwari.studence.proto.htmlWidgets.ARGBPb aegbForegroundColor = 10;</code>
   */
  @java.lang.Override
  public com.tiwari.studence.proto.htmlWidgets.ARGBPbOrBuilder getAegbForegroundColorOrBuilder() {
    return aegbForegroundColor_ == null ? com.tiwari.studence.proto.htmlWidgets.ARGBPb.getDefaultInstance() : aegbForegroundColor_;
  }

  public static final int HEXCODEFOREGROUNDCOLOR_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private volatile java.lang.Object hexCodeForegroundColor_ = "";
  /**
   * <code>string hexCodeForegroundColor = 11;</code>
   * @return The hexCodeForegroundColor.
   */
  @java.lang.Override
  public java.lang.String getHexCodeForegroundColor() {
    java.lang.Object ref = hexCodeForegroundColor_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      hexCodeForegroundColor_ = s;
      return s;
    }
  }
  /**
   * <code>string hexCodeForegroundColor = 11;</code>
   * @return The bytes for hexCodeForegroundColor.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHexCodeForegroundColorBytes() {
    java.lang.Object ref = hexCodeForegroundColor_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      hexCodeForegroundColor_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (colorType_ != com.tiwari.studence.proto.htmlWidgets.ColorTypeEnum.UNKNOWN_COLOR_TYPE.getNumber()) {
      output.writeEnum(1, colorType_);
    }
    if (colorInType_ != com.tiwari.studence.proto.htmlWidgets.ColorInTypeEnum.UNKNOWN_COLOR_IN_TYPE.getNumber()) {
      output.writeEnum(2, colorInType_);
    }
    if (rgboBackgroundColor_ != null) {
      output.writeMessage(3, getRgboBackgroundColor());
    }
    if (argbBackgroundColor_ != null) {
      output.writeMessage(4, getArgbBackgroundColor());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hexCodeBackgroundColor_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, hexCodeBackgroundColor_);
    }
    if (rgboFontColor_ != null) {
      output.writeMessage(6, getRgboFontColor());
    }
    if (aegbFontColor_ != null) {
      output.writeMessage(7, getAegbFontColor());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hexCodefontColor_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, hexCodefontColor_);
    }
    if (rgboForegroundColor_ != null) {
      output.writeMessage(9, getRgboForegroundColor());
    }
    if (aegbForegroundColor_ != null) {
      output.writeMessage(10, getAegbForegroundColor());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hexCodeForegroundColor_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, hexCodeForegroundColor_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (colorType_ != com.tiwari.studence.proto.htmlWidgets.ColorTypeEnum.UNKNOWN_COLOR_TYPE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, colorType_);
    }
    if (colorInType_ != com.tiwari.studence.proto.htmlWidgets.ColorInTypeEnum.UNKNOWN_COLOR_IN_TYPE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, colorInType_);
    }
    if (rgboBackgroundColor_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getRgboBackgroundColor());
    }
    if (argbBackgroundColor_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getArgbBackgroundColor());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hexCodeBackgroundColor_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, hexCodeBackgroundColor_);
    }
    if (rgboFontColor_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getRgboFontColor());
    }
    if (aegbFontColor_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getAegbFontColor());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hexCodefontColor_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, hexCodefontColor_);
    }
    if (rgboForegroundColor_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getRgboForegroundColor());
    }
    if (aegbForegroundColor_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getAegbForegroundColor());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hexCodeForegroundColor_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, hexCodeForegroundColor_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tiwari.studence.proto.htmlWidgets.ColorPb)) {
      return super.equals(obj);
    }
    com.tiwari.studence.proto.htmlWidgets.ColorPb other = (com.tiwari.studence.proto.htmlWidgets.ColorPb) obj;

    if (colorType_ != other.colorType_) return false;
    if (colorInType_ != other.colorInType_) return false;
    if (hasRgboBackgroundColor() != other.hasRgboBackgroundColor()) return false;
    if (hasRgboBackgroundColor()) {
      if (!getRgboBackgroundColor()
          .equals(other.getRgboBackgroundColor())) return false;
    }
    if (hasArgbBackgroundColor() != other.hasArgbBackgroundColor()) return false;
    if (hasArgbBackgroundColor()) {
      if (!getArgbBackgroundColor()
          .equals(other.getArgbBackgroundColor())) return false;
    }
    if (!getHexCodeBackgroundColor()
        .equals(other.getHexCodeBackgroundColor())) return false;
    if (hasRgboFontColor() != other.hasRgboFontColor()) return false;
    if (hasRgboFontColor()) {
      if (!getRgboFontColor()
          .equals(other.getRgboFontColor())) return false;
    }
    if (hasAegbFontColor() != other.hasAegbFontColor()) return false;
    if (hasAegbFontColor()) {
      if (!getAegbFontColor()
          .equals(other.getAegbFontColor())) return false;
    }
    if (!getHexCodefontColor()
        .equals(other.getHexCodefontColor())) return false;
    if (hasRgboForegroundColor() != other.hasRgboForegroundColor()) return false;
    if (hasRgboForegroundColor()) {
      if (!getRgboForegroundColor()
          .equals(other.getRgboForegroundColor())) return false;
    }
    if (hasAegbForegroundColor() != other.hasAegbForegroundColor()) return false;
    if (hasAegbForegroundColor()) {
      if (!getAegbForegroundColor()
          .equals(other.getAegbForegroundColor())) return false;
    }
    if (!getHexCodeForegroundColor()
        .equals(other.getHexCodeForegroundColor())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COLORTYPE_FIELD_NUMBER;
    hash = (53 * hash) + colorType_;
    hash = (37 * hash) + COLORINTYPE_FIELD_NUMBER;
    hash = (53 * hash) + colorInType_;
    if (hasRgboBackgroundColor()) {
      hash = (37 * hash) + RGBOBACKGROUNDCOLOR_FIELD_NUMBER;
      hash = (53 * hash) + getRgboBackgroundColor().hashCode();
    }
    if (hasArgbBackgroundColor()) {
      hash = (37 * hash) + ARGBBACKGROUNDCOLOR_FIELD_NUMBER;
      hash = (53 * hash) + getArgbBackgroundColor().hashCode();
    }
    hash = (37 * hash) + HEXCODEBACKGROUNDCOLOR_FIELD_NUMBER;
    hash = (53 * hash) + getHexCodeBackgroundColor().hashCode();
    if (hasRgboFontColor()) {
      hash = (37 * hash) + RGBOFONTCOLOR_FIELD_NUMBER;
      hash = (53 * hash) + getRgboFontColor().hashCode();
    }
    if (hasAegbFontColor()) {
      hash = (37 * hash) + AEGBFONTCOLOR_FIELD_NUMBER;
      hash = (53 * hash) + getAegbFontColor().hashCode();
    }
    hash = (37 * hash) + HEXCODEFONTCOLOR_FIELD_NUMBER;
    hash = (53 * hash) + getHexCodefontColor().hashCode();
    if (hasRgboForegroundColor()) {
      hash = (37 * hash) + RGBOFOREGROUNDCOLOR_FIELD_NUMBER;
      hash = (53 * hash) + getRgboForegroundColor().hashCode();
    }
    if (hasAegbForegroundColor()) {
      hash = (37 * hash) + AEGBFOREGROUNDCOLOR_FIELD_NUMBER;
      hash = (53 * hash) + getAegbForegroundColor().hashCode();
    }
    hash = (37 * hash) + HEXCODEFOREGROUNDCOLOR_FIELD_NUMBER;
    hash = (53 * hash) + getHexCodeForegroundColor().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tiwari.studence.proto.htmlWidgets.ColorPb parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tiwari.studence.proto.htmlWidgets.ColorPb parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tiwari.studence.proto.htmlWidgets.ColorPb parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tiwari.studence.proto.htmlWidgets.ColorPb parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tiwari.studence.proto.htmlWidgets.ColorPb parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tiwari.studence.proto.htmlWidgets.ColorPb parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tiwari.studence.proto.htmlWidgets.ColorPb parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tiwari.studence.proto.htmlWidgets.ColorPb parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tiwari.studence.proto.htmlWidgets.ColorPb parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tiwari.studence.proto.htmlWidgets.ColorPb parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tiwari.studence.proto.htmlWidgets.ColorPb parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tiwari.studence.proto.htmlWidgets.ColorPb parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tiwari.studence.proto.htmlWidgets.ColorPb prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.tiwari.studence.proto.htmlWidgets.ColorPb}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.tiwari.studence.proto.htmlWidgets.ColorPb)
      com.tiwari.studence.proto.htmlWidgets.ColorPbOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tiwari.studence.proto.htmlWidgets.HtmlWidgets.internal_static_com_tiwari_studence_proto_htmlWidgets_ColorPb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tiwari.studence.proto.htmlWidgets.HtmlWidgets.internal_static_com_tiwari_studence_proto_htmlWidgets_ColorPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tiwari.studence.proto.htmlWidgets.ColorPb.class, com.tiwari.studence.proto.htmlWidgets.ColorPb.Builder.class);
    }

    // Construct using com.tiwari.studence.proto.htmlWidgets.ColorPb.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      colorType_ = 0;
      colorInType_ = 0;
      rgboBackgroundColor_ = null;
      if (rgboBackgroundColorBuilder_ != null) {
        rgboBackgroundColorBuilder_.dispose();
        rgboBackgroundColorBuilder_ = null;
      }
      argbBackgroundColor_ = null;
      if (argbBackgroundColorBuilder_ != null) {
        argbBackgroundColorBuilder_.dispose();
        argbBackgroundColorBuilder_ = null;
      }
      hexCodeBackgroundColor_ = "";
      rgboFontColor_ = null;
      if (rgboFontColorBuilder_ != null) {
        rgboFontColorBuilder_.dispose();
        rgboFontColorBuilder_ = null;
      }
      aegbFontColor_ = null;
      if (aegbFontColorBuilder_ != null) {
        aegbFontColorBuilder_.dispose();
        aegbFontColorBuilder_ = null;
      }
      hexCodefontColor_ = "";
      rgboForegroundColor_ = null;
      if (rgboForegroundColorBuilder_ != null) {
        rgboForegroundColorBuilder_.dispose();
        rgboForegroundColorBuilder_ = null;
      }
      aegbForegroundColor_ = null;
      if (aegbForegroundColorBuilder_ != null) {
        aegbForegroundColorBuilder_.dispose();
        aegbForegroundColorBuilder_ = null;
      }
      hexCodeForegroundColor_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tiwari.studence.proto.htmlWidgets.HtmlWidgets.internal_static_com_tiwari_studence_proto_htmlWidgets_ColorPb_descriptor;
    }

    @java.lang.Override
    public com.tiwari.studence.proto.htmlWidgets.ColorPb getDefaultInstanceForType() {
      return com.tiwari.studence.proto.htmlWidgets.ColorPb.getDefaultInstance();
    }

    @java.lang.Override
    public com.tiwari.studence.proto.htmlWidgets.ColorPb build() {
      com.tiwari.studence.proto.htmlWidgets.ColorPb result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tiwari.studence.proto.htmlWidgets.ColorPb buildPartial() {
      com.tiwari.studence.proto.htmlWidgets.ColorPb result = new com.tiwari.studence.proto.htmlWidgets.ColorPb(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.tiwari.studence.proto.htmlWidgets.ColorPb result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.colorType_ = colorType_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.colorInType_ = colorInType_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.rgboBackgroundColor_ = rgboBackgroundColorBuilder_ == null
            ? rgboBackgroundColor_
            : rgboBackgroundColorBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.argbBackgroundColor_ = argbBackgroundColorBuilder_ == null
            ? argbBackgroundColor_
            : argbBackgroundColorBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.hexCodeBackgroundColor_ = hexCodeBackgroundColor_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.rgboFontColor_ = rgboFontColorBuilder_ == null
            ? rgboFontColor_
            : rgboFontColorBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.aegbFontColor_ = aegbFontColorBuilder_ == null
            ? aegbFontColor_
            : aegbFontColorBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.hexCodefontColor_ = hexCodefontColor_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.rgboForegroundColor_ = rgboForegroundColorBuilder_ == null
            ? rgboForegroundColor_
            : rgboForegroundColorBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.aegbForegroundColor_ = aegbForegroundColorBuilder_ == null
            ? aegbForegroundColor_
            : aegbForegroundColorBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.hexCodeForegroundColor_ = hexCodeForegroundColor_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tiwari.studence.proto.htmlWidgets.ColorPb) {
        return mergeFrom((com.tiwari.studence.proto.htmlWidgets.ColorPb)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tiwari.studence.proto.htmlWidgets.ColorPb other) {
      if (other == com.tiwari.studence.proto.htmlWidgets.ColorPb.getDefaultInstance()) return this;
      if (other.colorType_ != 0) {
        setColorTypeValue(other.getColorTypeValue());
      }
      if (other.colorInType_ != 0) {
        setColorInTypeValue(other.getColorInTypeValue());
      }
      if (other.hasRgboBackgroundColor()) {
        mergeRgboBackgroundColor(other.getRgboBackgroundColor());
      }
      if (other.hasArgbBackgroundColor()) {
        mergeArgbBackgroundColor(other.getArgbBackgroundColor());
      }
      if (!other.getHexCodeBackgroundColor().isEmpty()) {
        hexCodeBackgroundColor_ = other.hexCodeBackgroundColor_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.hasRgboFontColor()) {
        mergeRgboFontColor(other.getRgboFontColor());
      }
      if (other.hasAegbFontColor()) {
        mergeAegbFontColor(other.getAegbFontColor());
      }
      if (!other.getHexCodefontColor().isEmpty()) {
        hexCodefontColor_ = other.hexCodefontColor_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (other.hasRgboForegroundColor()) {
        mergeRgboForegroundColor(other.getRgboForegroundColor());
      }
      if (other.hasAegbForegroundColor()) {
        mergeAegbForegroundColor(other.getAegbForegroundColor());
      }
      if (!other.getHexCodeForegroundColor().isEmpty()) {
        hexCodeForegroundColor_ = other.hexCodeForegroundColor_;
        bitField0_ |= 0x00000400;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              colorType_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              colorInType_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              input.readMessage(
                  getRgboBackgroundColorFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getArgbBackgroundColorFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              hexCodeBackgroundColor_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getRgboFontColorFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getAegbFontColorFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              hexCodefontColor_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              input.readMessage(
                  getRgboForegroundColorFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              input.readMessage(
                  getAegbForegroundColorFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 90: {
              hexCodeForegroundColor_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int colorType_ = 0;
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.ColorTypeEnum colorType = 1;</code>
     * @return The enum numeric value on the wire for colorType.
     */
    @java.lang.Override public int getColorTypeValue() {
      return colorType_;
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.ColorTypeEnum colorType = 1;</code>
     * @param value The enum numeric value on the wire for colorType to set.
     * @return This builder for chaining.
     */
    public Builder setColorTypeValue(int value) {
      colorType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.ColorTypeEnum colorType = 1;</code>
     * @return The colorType.
     */
    @java.lang.Override
    public com.tiwari.studence.proto.htmlWidgets.ColorTypeEnum getColorType() {
      com.tiwari.studence.proto.htmlWidgets.ColorTypeEnum result = com.tiwari.studence.proto.htmlWidgets.ColorTypeEnum.forNumber(colorType_);
      return result == null ? com.tiwari.studence.proto.htmlWidgets.ColorTypeEnum.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.ColorTypeEnum colorType = 1;</code>
     * @param value The colorType to set.
     * @return This builder for chaining.
     */
    public Builder setColorType(com.tiwari.studence.proto.htmlWidgets.ColorTypeEnum value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      colorType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.ColorTypeEnum colorType = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearColorType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      colorType_ = 0;
      onChanged();
      return this;
    }

    private int colorInType_ = 0;
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.ColorInTypeEnum colorInType = 2;</code>
     * @return The enum numeric value on the wire for colorInType.
     */
    @java.lang.Override public int getColorInTypeValue() {
      return colorInType_;
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.ColorInTypeEnum colorInType = 2;</code>
     * @param value The enum numeric value on the wire for colorInType to set.
     * @return This builder for chaining.
     */
    public Builder setColorInTypeValue(int value) {
      colorInType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.ColorInTypeEnum colorInType = 2;</code>
     * @return The colorInType.
     */
    @java.lang.Override
    public com.tiwari.studence.proto.htmlWidgets.ColorInTypeEnum getColorInType() {
      com.tiwari.studence.proto.htmlWidgets.ColorInTypeEnum result = com.tiwari.studence.proto.htmlWidgets.ColorInTypeEnum.forNumber(colorInType_);
      return result == null ? com.tiwari.studence.proto.htmlWidgets.ColorInTypeEnum.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.ColorInTypeEnum colorInType = 2;</code>
     * @param value The colorInType to set.
     * @return This builder for chaining.
     */
    public Builder setColorInType(com.tiwari.studence.proto.htmlWidgets.ColorInTypeEnum value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      colorInType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.ColorInTypeEnum colorInType = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearColorInType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      colorInType_ = 0;
      onChanged();
      return this;
    }

    private com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboBackgroundColor_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tiwari.studence.proto.htmlWidgets.RGBOPb, com.tiwari.studence.proto.htmlWidgets.RGBOPb.Builder, com.tiwari.studence.proto.htmlWidgets.RGBOPbOrBuilder> rgboBackgroundColorBuilder_;
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboBackgroundColor = 3;</code>
     * @return Whether the rgboBackgroundColor field is set.
     */
    public boolean hasRgboBackgroundColor() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboBackgroundColor = 3;</code>
     * @return The rgboBackgroundColor.
     */
    public com.tiwari.studence.proto.htmlWidgets.RGBOPb getRgboBackgroundColor() {
      if (rgboBackgroundColorBuilder_ == null) {
        return rgboBackgroundColor_ == null ? com.tiwari.studence.proto.htmlWidgets.RGBOPb.getDefaultInstance() : rgboBackgroundColor_;
      } else {
        return rgboBackgroundColorBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboBackgroundColor = 3;</code>
     */
    public Builder setRgboBackgroundColor(com.tiwari.studence.proto.htmlWidgets.RGBOPb value) {
      if (rgboBackgroundColorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        rgboBackgroundColor_ = value;
      } else {
        rgboBackgroundColorBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboBackgroundColor = 3;</code>
     */
    public Builder setRgboBackgroundColor(
        com.tiwari.studence.proto.htmlWidgets.RGBOPb.Builder builderForValue) {
      if (rgboBackgroundColorBuilder_ == null) {
        rgboBackgroundColor_ = builderForValue.build();
      } else {
        rgboBackgroundColorBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboBackgroundColor = 3;</code>
     */
    public Builder mergeRgboBackgroundColor(com.tiwari.studence.proto.htmlWidgets.RGBOPb value) {
      if (rgboBackgroundColorBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          rgboBackgroundColor_ != null &&
          rgboBackgroundColor_ != com.tiwari.studence.proto.htmlWidgets.RGBOPb.getDefaultInstance()) {
          getRgboBackgroundColorBuilder().mergeFrom(value);
        } else {
          rgboBackgroundColor_ = value;
        }
      } else {
        rgboBackgroundColorBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboBackgroundColor = 3;</code>
     */
    public Builder clearRgboBackgroundColor() {
      bitField0_ = (bitField0_ & ~0x00000004);
      rgboBackgroundColor_ = null;
      if (rgboBackgroundColorBuilder_ != null) {
        rgboBackgroundColorBuilder_.dispose();
        rgboBackgroundColorBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboBackgroundColor = 3;</code>
     */
    public com.tiwari.studence.proto.htmlWidgets.RGBOPb.Builder getRgboBackgroundColorBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getRgboBackgroundColorFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboBackgroundColor = 3;</code>
     */
    public com.tiwari.studence.proto.htmlWidgets.RGBOPbOrBuilder getRgboBackgroundColorOrBuilder() {
      if (rgboBackgroundColorBuilder_ != null) {
        return rgboBackgroundColorBuilder_.getMessageOrBuilder();
      } else {
        return rgboBackgroundColor_ == null ?
            com.tiwari.studence.proto.htmlWidgets.RGBOPb.getDefaultInstance() : rgboBackgroundColor_;
      }
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboBackgroundColor = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tiwari.studence.proto.htmlWidgets.RGBOPb, com.tiwari.studence.proto.htmlWidgets.RGBOPb.Builder, com.tiwari.studence.proto.htmlWidgets.RGBOPbOrBuilder> 
        getRgboBackgroundColorFieldBuilder() {
      if (rgboBackgroundColorBuilder_ == null) {
        rgboBackgroundColorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.tiwari.studence.proto.htmlWidgets.RGBOPb, com.tiwari.studence.proto.htmlWidgets.RGBOPb.Builder, com.tiwari.studence.proto.htmlWidgets.RGBOPbOrBuilder>(
                getRgboBackgroundColor(),
                getParentForChildren(),
                isClean());
        rgboBackgroundColor_ = null;
      }
      return rgboBackgroundColorBuilder_;
    }

    private com.tiwari.studence.proto.htmlWidgets.ARGBPb argbBackgroundColor_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tiwari.studence.proto.htmlWidgets.ARGBPb, com.tiwari.studence.proto.htmlWidgets.ARGBPb.Builder, com.tiwari.studence.proto.htmlWidgets.ARGBPbOrBuilder> argbBackgroundColorBuilder_;
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.ARGBPb argbBackgroundColor = 4;</code>
     * @return Whether the argbBackgroundColor field is set.
     */
    public boolean hasArgbBackgroundColor() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.ARGBPb argbBackgroundColor = 4;</code>
     * @return The argbBackgroundColor.
     */
    public com.tiwari.studence.proto.htmlWidgets.ARGBPb getArgbBackgroundColor() {
      if (argbBackgroundColorBuilder_ == null) {
        return argbBackgroundColor_ == null ? com.tiwari.studence.proto.htmlWidgets.ARGBPb.getDefaultInstance() : argbBackgroundColor_;
      } else {
        return argbBackgroundColorBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.ARGBPb argbBackgroundColor = 4;</code>
     */
    public Builder setArgbBackgroundColor(com.tiwari.studence.proto.htmlWidgets.ARGBPb value) {
      if (argbBackgroundColorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        argbBackgroundColor_ = value;
      } else {
        argbBackgroundColorBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.ARGBPb argbBackgroundColor = 4;</code>
     */
    public Builder setArgbBackgroundColor(
        com.tiwari.studence.proto.htmlWidgets.ARGBPb.Builder builderForValue) {
      if (argbBackgroundColorBuilder_ == null) {
        argbBackgroundColor_ = builderForValue.build();
      } else {
        argbBackgroundColorBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.ARGBPb argbBackgroundColor = 4;</code>
     */
    public Builder mergeArgbBackgroundColor(com.tiwari.studence.proto.htmlWidgets.ARGBPb value) {
      if (argbBackgroundColorBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          argbBackgroundColor_ != null &&
          argbBackgroundColor_ != com.tiwari.studence.proto.htmlWidgets.ARGBPb.getDefaultInstance()) {
          getArgbBackgroundColorBuilder().mergeFrom(value);
        } else {
          argbBackgroundColor_ = value;
        }
      } else {
        argbBackgroundColorBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.ARGBPb argbBackgroundColor = 4;</code>
     */
    public Builder clearArgbBackgroundColor() {
      bitField0_ = (bitField0_ & ~0x00000008);
      argbBackgroundColor_ = null;
      if (argbBackgroundColorBuilder_ != null) {
        argbBackgroundColorBuilder_.dispose();
        argbBackgroundColorBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.ARGBPb argbBackgroundColor = 4;</code>
     */
    public com.tiwari.studence.proto.htmlWidgets.ARGBPb.Builder getArgbBackgroundColorBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getArgbBackgroundColorFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.ARGBPb argbBackgroundColor = 4;</code>
     */
    public com.tiwari.studence.proto.htmlWidgets.ARGBPbOrBuilder getArgbBackgroundColorOrBuilder() {
      if (argbBackgroundColorBuilder_ != null) {
        return argbBackgroundColorBuilder_.getMessageOrBuilder();
      } else {
        return argbBackgroundColor_ == null ?
            com.tiwari.studence.proto.htmlWidgets.ARGBPb.getDefaultInstance() : argbBackgroundColor_;
      }
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.ARGBPb argbBackgroundColor = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tiwari.studence.proto.htmlWidgets.ARGBPb, com.tiwari.studence.proto.htmlWidgets.ARGBPb.Builder, com.tiwari.studence.proto.htmlWidgets.ARGBPbOrBuilder> 
        getArgbBackgroundColorFieldBuilder() {
      if (argbBackgroundColorBuilder_ == null) {
        argbBackgroundColorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.tiwari.studence.proto.htmlWidgets.ARGBPb, com.tiwari.studence.proto.htmlWidgets.ARGBPb.Builder, com.tiwari.studence.proto.htmlWidgets.ARGBPbOrBuilder>(
                getArgbBackgroundColor(),
                getParentForChildren(),
                isClean());
        argbBackgroundColor_ = null;
      }
      return argbBackgroundColorBuilder_;
    }

    private java.lang.Object hexCodeBackgroundColor_ = "";
    /**
     * <code>string hexCodeBackgroundColor = 5;</code>
     * @return The hexCodeBackgroundColor.
     */
    public java.lang.String getHexCodeBackgroundColor() {
      java.lang.Object ref = hexCodeBackgroundColor_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hexCodeBackgroundColor_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string hexCodeBackgroundColor = 5;</code>
     * @return The bytes for hexCodeBackgroundColor.
     */
    public com.google.protobuf.ByteString
        getHexCodeBackgroundColorBytes() {
      java.lang.Object ref = hexCodeBackgroundColor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hexCodeBackgroundColor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string hexCodeBackgroundColor = 5;</code>
     * @param value The hexCodeBackgroundColor to set.
     * @return This builder for chaining.
     */
    public Builder setHexCodeBackgroundColor(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      hexCodeBackgroundColor_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string hexCodeBackgroundColor = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearHexCodeBackgroundColor() {
      hexCodeBackgroundColor_ = getDefaultInstance().getHexCodeBackgroundColor();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string hexCodeBackgroundColor = 5;</code>
     * @param value The bytes for hexCodeBackgroundColor to set.
     * @return This builder for chaining.
     */
    public Builder setHexCodeBackgroundColorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      hexCodeBackgroundColor_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboFontColor_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tiwari.studence.proto.htmlWidgets.RGBOPb, com.tiwari.studence.proto.htmlWidgets.RGBOPb.Builder, com.tiwari.studence.proto.htmlWidgets.RGBOPbOrBuilder> rgboFontColorBuilder_;
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboFontColor = 6;</code>
     * @return Whether the rgboFontColor field is set.
     */
    public boolean hasRgboFontColor() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboFontColor = 6;</code>
     * @return The rgboFontColor.
     */
    public com.tiwari.studence.proto.htmlWidgets.RGBOPb getRgboFontColor() {
      if (rgboFontColorBuilder_ == null) {
        return rgboFontColor_ == null ? com.tiwari.studence.proto.htmlWidgets.RGBOPb.getDefaultInstance() : rgboFontColor_;
      } else {
        return rgboFontColorBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboFontColor = 6;</code>
     */
    public Builder setRgboFontColor(com.tiwari.studence.proto.htmlWidgets.RGBOPb value) {
      if (rgboFontColorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        rgboFontColor_ = value;
      } else {
        rgboFontColorBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboFontColor = 6;</code>
     */
    public Builder setRgboFontColor(
        com.tiwari.studence.proto.htmlWidgets.RGBOPb.Builder builderForValue) {
      if (rgboFontColorBuilder_ == null) {
        rgboFontColor_ = builderForValue.build();
      } else {
        rgboFontColorBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboFontColor = 6;</code>
     */
    public Builder mergeRgboFontColor(com.tiwari.studence.proto.htmlWidgets.RGBOPb value) {
      if (rgboFontColorBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          rgboFontColor_ != null &&
          rgboFontColor_ != com.tiwari.studence.proto.htmlWidgets.RGBOPb.getDefaultInstance()) {
          getRgboFontColorBuilder().mergeFrom(value);
        } else {
          rgboFontColor_ = value;
        }
      } else {
        rgboFontColorBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboFontColor = 6;</code>
     */
    public Builder clearRgboFontColor() {
      bitField0_ = (bitField0_ & ~0x00000020);
      rgboFontColor_ = null;
      if (rgboFontColorBuilder_ != null) {
        rgboFontColorBuilder_.dispose();
        rgboFontColorBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboFontColor = 6;</code>
     */
    public com.tiwari.studence.proto.htmlWidgets.RGBOPb.Builder getRgboFontColorBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getRgboFontColorFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboFontColor = 6;</code>
     */
    public com.tiwari.studence.proto.htmlWidgets.RGBOPbOrBuilder getRgboFontColorOrBuilder() {
      if (rgboFontColorBuilder_ != null) {
        return rgboFontColorBuilder_.getMessageOrBuilder();
      } else {
        return rgboFontColor_ == null ?
            com.tiwari.studence.proto.htmlWidgets.RGBOPb.getDefaultInstance() : rgboFontColor_;
      }
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboFontColor = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tiwari.studence.proto.htmlWidgets.RGBOPb, com.tiwari.studence.proto.htmlWidgets.RGBOPb.Builder, com.tiwari.studence.proto.htmlWidgets.RGBOPbOrBuilder> 
        getRgboFontColorFieldBuilder() {
      if (rgboFontColorBuilder_ == null) {
        rgboFontColorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.tiwari.studence.proto.htmlWidgets.RGBOPb, com.tiwari.studence.proto.htmlWidgets.RGBOPb.Builder, com.tiwari.studence.proto.htmlWidgets.RGBOPbOrBuilder>(
                getRgboFontColor(),
                getParentForChildren(),
                isClean());
        rgboFontColor_ = null;
      }
      return rgboFontColorBuilder_;
    }

    private com.tiwari.studence.proto.htmlWidgets.ARGBPb aegbFontColor_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tiwari.studence.proto.htmlWidgets.ARGBPb, com.tiwari.studence.proto.htmlWidgets.ARGBPb.Builder, com.tiwari.studence.proto.htmlWidgets.ARGBPbOrBuilder> aegbFontColorBuilder_;
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.ARGBPb aegbFontColor = 7;</code>
     * @return Whether the aegbFontColor field is set.
     */
    public boolean hasAegbFontColor() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.ARGBPb aegbFontColor = 7;</code>
     * @return The aegbFontColor.
     */
    public com.tiwari.studence.proto.htmlWidgets.ARGBPb getAegbFontColor() {
      if (aegbFontColorBuilder_ == null) {
        return aegbFontColor_ == null ? com.tiwari.studence.proto.htmlWidgets.ARGBPb.getDefaultInstance() : aegbFontColor_;
      } else {
        return aegbFontColorBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.ARGBPb aegbFontColor = 7;</code>
     */
    public Builder setAegbFontColor(com.tiwari.studence.proto.htmlWidgets.ARGBPb value) {
      if (aegbFontColorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        aegbFontColor_ = value;
      } else {
        aegbFontColorBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.ARGBPb aegbFontColor = 7;</code>
     */
    public Builder setAegbFontColor(
        com.tiwari.studence.proto.htmlWidgets.ARGBPb.Builder builderForValue) {
      if (aegbFontColorBuilder_ == null) {
        aegbFontColor_ = builderForValue.build();
      } else {
        aegbFontColorBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.ARGBPb aegbFontColor = 7;</code>
     */
    public Builder mergeAegbFontColor(com.tiwari.studence.proto.htmlWidgets.ARGBPb value) {
      if (aegbFontColorBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          aegbFontColor_ != null &&
          aegbFontColor_ != com.tiwari.studence.proto.htmlWidgets.ARGBPb.getDefaultInstance()) {
          getAegbFontColorBuilder().mergeFrom(value);
        } else {
          aegbFontColor_ = value;
        }
      } else {
        aegbFontColorBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.ARGBPb aegbFontColor = 7;</code>
     */
    public Builder clearAegbFontColor() {
      bitField0_ = (bitField0_ & ~0x00000040);
      aegbFontColor_ = null;
      if (aegbFontColorBuilder_ != null) {
        aegbFontColorBuilder_.dispose();
        aegbFontColorBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.ARGBPb aegbFontColor = 7;</code>
     */
    public com.tiwari.studence.proto.htmlWidgets.ARGBPb.Builder getAegbFontColorBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getAegbFontColorFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.ARGBPb aegbFontColor = 7;</code>
     */
    public com.tiwari.studence.proto.htmlWidgets.ARGBPbOrBuilder getAegbFontColorOrBuilder() {
      if (aegbFontColorBuilder_ != null) {
        return aegbFontColorBuilder_.getMessageOrBuilder();
      } else {
        return aegbFontColor_ == null ?
            com.tiwari.studence.proto.htmlWidgets.ARGBPb.getDefaultInstance() : aegbFontColor_;
      }
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.ARGBPb aegbFontColor = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tiwari.studence.proto.htmlWidgets.ARGBPb, com.tiwari.studence.proto.htmlWidgets.ARGBPb.Builder, com.tiwari.studence.proto.htmlWidgets.ARGBPbOrBuilder> 
        getAegbFontColorFieldBuilder() {
      if (aegbFontColorBuilder_ == null) {
        aegbFontColorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.tiwari.studence.proto.htmlWidgets.ARGBPb, com.tiwari.studence.proto.htmlWidgets.ARGBPb.Builder, com.tiwari.studence.proto.htmlWidgets.ARGBPbOrBuilder>(
                getAegbFontColor(),
                getParentForChildren(),
                isClean());
        aegbFontColor_ = null;
      }
      return aegbFontColorBuilder_;
    }

    private java.lang.Object hexCodefontColor_ = "";
    /**
     * <code>string hexCodefontColor = 8;</code>
     * @return The hexCodefontColor.
     */
    public java.lang.String getHexCodefontColor() {
      java.lang.Object ref = hexCodefontColor_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hexCodefontColor_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string hexCodefontColor = 8;</code>
     * @return The bytes for hexCodefontColor.
     */
    public com.google.protobuf.ByteString
        getHexCodefontColorBytes() {
      java.lang.Object ref = hexCodefontColor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hexCodefontColor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string hexCodefontColor = 8;</code>
     * @param value The hexCodefontColor to set.
     * @return This builder for chaining.
     */
    public Builder setHexCodefontColor(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      hexCodefontColor_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string hexCodefontColor = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearHexCodefontColor() {
      hexCodefontColor_ = getDefaultInstance().getHexCodefontColor();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string hexCodefontColor = 8;</code>
     * @param value The bytes for hexCodefontColor to set.
     * @return This builder for chaining.
     */
    public Builder setHexCodefontColorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      hexCodefontColor_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboForegroundColor_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tiwari.studence.proto.htmlWidgets.RGBOPb, com.tiwari.studence.proto.htmlWidgets.RGBOPb.Builder, com.tiwari.studence.proto.htmlWidgets.RGBOPbOrBuilder> rgboForegroundColorBuilder_;
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboForegroundColor = 9;</code>
     * @return Whether the rgboForegroundColor field is set.
     */
    public boolean hasRgboForegroundColor() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboForegroundColor = 9;</code>
     * @return The rgboForegroundColor.
     */
    public com.tiwari.studence.proto.htmlWidgets.RGBOPb getRgboForegroundColor() {
      if (rgboForegroundColorBuilder_ == null) {
        return rgboForegroundColor_ == null ? com.tiwari.studence.proto.htmlWidgets.RGBOPb.getDefaultInstance() : rgboForegroundColor_;
      } else {
        return rgboForegroundColorBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboForegroundColor = 9;</code>
     */
    public Builder setRgboForegroundColor(com.tiwari.studence.proto.htmlWidgets.RGBOPb value) {
      if (rgboForegroundColorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        rgboForegroundColor_ = value;
      } else {
        rgboForegroundColorBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboForegroundColor = 9;</code>
     */
    public Builder setRgboForegroundColor(
        com.tiwari.studence.proto.htmlWidgets.RGBOPb.Builder builderForValue) {
      if (rgboForegroundColorBuilder_ == null) {
        rgboForegroundColor_ = builderForValue.build();
      } else {
        rgboForegroundColorBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboForegroundColor = 9;</code>
     */
    public Builder mergeRgboForegroundColor(com.tiwari.studence.proto.htmlWidgets.RGBOPb value) {
      if (rgboForegroundColorBuilder_ == null) {
        if (((bitField0_ & 0x00000100) != 0) &&
          rgboForegroundColor_ != null &&
          rgboForegroundColor_ != com.tiwari.studence.proto.htmlWidgets.RGBOPb.getDefaultInstance()) {
          getRgboForegroundColorBuilder().mergeFrom(value);
        } else {
          rgboForegroundColor_ = value;
        }
      } else {
        rgboForegroundColorBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboForegroundColor = 9;</code>
     */
    public Builder clearRgboForegroundColor() {
      bitField0_ = (bitField0_ & ~0x00000100);
      rgboForegroundColor_ = null;
      if (rgboForegroundColorBuilder_ != null) {
        rgboForegroundColorBuilder_.dispose();
        rgboForegroundColorBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboForegroundColor = 9;</code>
     */
    public com.tiwari.studence.proto.htmlWidgets.RGBOPb.Builder getRgboForegroundColorBuilder() {
      bitField0_ |= 0x00000100;
      onChanged();
      return getRgboForegroundColorFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboForegroundColor = 9;</code>
     */
    public com.tiwari.studence.proto.htmlWidgets.RGBOPbOrBuilder getRgboForegroundColorOrBuilder() {
      if (rgboForegroundColorBuilder_ != null) {
        return rgboForegroundColorBuilder_.getMessageOrBuilder();
      } else {
        return rgboForegroundColor_ == null ?
            com.tiwari.studence.proto.htmlWidgets.RGBOPb.getDefaultInstance() : rgboForegroundColor_;
      }
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.RGBOPb rgboForegroundColor = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tiwari.studence.proto.htmlWidgets.RGBOPb, com.tiwari.studence.proto.htmlWidgets.RGBOPb.Builder, com.tiwari.studence.proto.htmlWidgets.RGBOPbOrBuilder> 
        getRgboForegroundColorFieldBuilder() {
      if (rgboForegroundColorBuilder_ == null) {
        rgboForegroundColorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.tiwari.studence.proto.htmlWidgets.RGBOPb, com.tiwari.studence.proto.htmlWidgets.RGBOPb.Builder, com.tiwari.studence.proto.htmlWidgets.RGBOPbOrBuilder>(
                getRgboForegroundColor(),
                getParentForChildren(),
                isClean());
        rgboForegroundColor_ = null;
      }
      return rgboForegroundColorBuilder_;
    }

    private com.tiwari.studence.proto.htmlWidgets.ARGBPb aegbForegroundColor_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tiwari.studence.proto.htmlWidgets.ARGBPb, com.tiwari.studence.proto.htmlWidgets.ARGBPb.Builder, com.tiwari.studence.proto.htmlWidgets.ARGBPbOrBuilder> aegbForegroundColorBuilder_;
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.ARGBPb aegbForegroundColor = 10;</code>
     * @return Whether the aegbForegroundColor field is set.
     */
    public boolean hasAegbForegroundColor() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.ARGBPb aegbForegroundColor = 10;</code>
     * @return The aegbForegroundColor.
     */
    public com.tiwari.studence.proto.htmlWidgets.ARGBPb getAegbForegroundColor() {
      if (aegbForegroundColorBuilder_ == null) {
        return aegbForegroundColor_ == null ? com.tiwari.studence.proto.htmlWidgets.ARGBPb.getDefaultInstance() : aegbForegroundColor_;
      } else {
        return aegbForegroundColorBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.ARGBPb aegbForegroundColor = 10;</code>
     */
    public Builder setAegbForegroundColor(com.tiwari.studence.proto.htmlWidgets.ARGBPb value) {
      if (aegbForegroundColorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        aegbForegroundColor_ = value;
      } else {
        aegbForegroundColorBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.ARGBPb aegbForegroundColor = 10;</code>
     */
    public Builder setAegbForegroundColor(
        com.tiwari.studence.proto.htmlWidgets.ARGBPb.Builder builderForValue) {
      if (aegbForegroundColorBuilder_ == null) {
        aegbForegroundColor_ = builderForValue.build();
      } else {
        aegbForegroundColorBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.ARGBPb aegbForegroundColor = 10;</code>
     */
    public Builder mergeAegbForegroundColor(com.tiwari.studence.proto.htmlWidgets.ARGBPb value) {
      if (aegbForegroundColorBuilder_ == null) {
        if (((bitField0_ & 0x00000200) != 0) &&
          aegbForegroundColor_ != null &&
          aegbForegroundColor_ != com.tiwari.studence.proto.htmlWidgets.ARGBPb.getDefaultInstance()) {
          getAegbForegroundColorBuilder().mergeFrom(value);
        } else {
          aegbForegroundColor_ = value;
        }
      } else {
        aegbForegroundColorBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.ARGBPb aegbForegroundColor = 10;</code>
     */
    public Builder clearAegbForegroundColor() {
      bitField0_ = (bitField0_ & ~0x00000200);
      aegbForegroundColor_ = null;
      if (aegbForegroundColorBuilder_ != null) {
        aegbForegroundColorBuilder_.dispose();
        aegbForegroundColorBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.ARGBPb aegbForegroundColor = 10;</code>
     */
    public com.tiwari.studence.proto.htmlWidgets.ARGBPb.Builder getAegbForegroundColorBuilder() {
      bitField0_ |= 0x00000200;
      onChanged();
      return getAegbForegroundColorFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.ARGBPb aegbForegroundColor = 10;</code>
     */
    public com.tiwari.studence.proto.htmlWidgets.ARGBPbOrBuilder getAegbForegroundColorOrBuilder() {
      if (aegbForegroundColorBuilder_ != null) {
        return aegbForegroundColorBuilder_.getMessageOrBuilder();
      } else {
        return aegbForegroundColor_ == null ?
            com.tiwari.studence.proto.htmlWidgets.ARGBPb.getDefaultInstance() : aegbForegroundColor_;
      }
    }
    /**
     * <code>.com.tiwari.studence.proto.htmlWidgets.ARGBPb aegbForegroundColor = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tiwari.studence.proto.htmlWidgets.ARGBPb, com.tiwari.studence.proto.htmlWidgets.ARGBPb.Builder, com.tiwari.studence.proto.htmlWidgets.ARGBPbOrBuilder> 
        getAegbForegroundColorFieldBuilder() {
      if (aegbForegroundColorBuilder_ == null) {
        aegbForegroundColorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.tiwari.studence.proto.htmlWidgets.ARGBPb, com.tiwari.studence.proto.htmlWidgets.ARGBPb.Builder, com.tiwari.studence.proto.htmlWidgets.ARGBPbOrBuilder>(
                getAegbForegroundColor(),
                getParentForChildren(),
                isClean());
        aegbForegroundColor_ = null;
      }
      return aegbForegroundColorBuilder_;
    }

    private java.lang.Object hexCodeForegroundColor_ = "";
    /**
     * <code>string hexCodeForegroundColor = 11;</code>
     * @return The hexCodeForegroundColor.
     */
    public java.lang.String getHexCodeForegroundColor() {
      java.lang.Object ref = hexCodeForegroundColor_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hexCodeForegroundColor_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string hexCodeForegroundColor = 11;</code>
     * @return The bytes for hexCodeForegroundColor.
     */
    public com.google.protobuf.ByteString
        getHexCodeForegroundColorBytes() {
      java.lang.Object ref = hexCodeForegroundColor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hexCodeForegroundColor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string hexCodeForegroundColor = 11;</code>
     * @param value The hexCodeForegroundColor to set.
     * @return This builder for chaining.
     */
    public Builder setHexCodeForegroundColor(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      hexCodeForegroundColor_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>string hexCodeForegroundColor = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearHexCodeForegroundColor() {
      hexCodeForegroundColor_ = getDefaultInstance().getHexCodeForegroundColor();
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }
    /**
     * <code>string hexCodeForegroundColor = 11;</code>
     * @param value The bytes for hexCodeForegroundColor to set.
     * @return This builder for chaining.
     */
    public Builder setHexCodeForegroundColorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      hexCodeForegroundColor_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.tiwari.studence.proto.htmlWidgets.ColorPb)
  }

  // @@protoc_insertion_point(class_scope:com.tiwari.studence.proto.htmlWidgets.ColorPb)
  private static final com.tiwari.studence.proto.htmlWidgets.ColorPb DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tiwari.studence.proto.htmlWidgets.ColorPb();
  }

  public static com.tiwari.studence.proto.htmlWidgets.ColorPb getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ColorPb>
      PARSER = new com.google.protobuf.AbstractParser<ColorPb>() {
    @java.lang.Override
    public ColorPb parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ColorPb> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ColorPb> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tiwari.studence.proto.htmlWidgets.ColorPb getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

