// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entityPb.proto

package com.tiwari.studence.proto.entity;

/**
 * Protobuf enum {@code com.tiwari.studence.proto.entity.AccessEnum}
 */
public enum AccessEnum
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNKNOW_ACCESS = 0;</code>
   */
  UNKNOW_ACCESS(0),
  /**
   * <code>EXPLICIT_DENY = 1;</code>
   */
  EXPLICIT_DENY(1),
  /**
   * <code>ALLOW = 2;</code>
   */
  ALLOW(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNKNOW_ACCESS = 0;</code>
   */
  public static final int UNKNOW_ACCESS_VALUE = 0;
  /**
   * <code>EXPLICIT_DENY = 1;</code>
   */
  public static final int EXPLICIT_DENY_VALUE = 1;
  /**
   * <code>ALLOW = 2;</code>
   */
  public static final int ALLOW_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static AccessEnum valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static AccessEnum forNumber(int value) {
    switch (value) {
      case 0: return UNKNOW_ACCESS;
      case 1: return EXPLICIT_DENY;
      case 2: return ALLOW;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<AccessEnum>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      AccessEnum> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<AccessEnum>() {
          public AccessEnum findValueByNumber(int number) {
            return AccessEnum.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.tiwari.studence.proto.entity.EntityPbOuterClass.getDescriptor().getEnumTypes().get(6);
  }

  private static final AccessEnum[] VALUES = values();

  public static AccessEnum valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private AccessEnum(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.tiwari.studence.proto.entity.AccessEnum)
}

