// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entityPb.proto

package com.tiwari.studence.proto.entity;

/**
 * Protobuf enum {@code com.tiwari.studence.proto.entity.NodeTypeUiPbEnum}
 */
public enum NodeTypeUiPbEnum
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNKNOWN_LEAF_NODE = 0;</code>
   */
  UNKNOWN_LEAF_NODE(0),
  /**
   * <code>LEAF_NODE = 1;</code>
   */
  LEAF_NODE(1),
  /**
   * <code>NON_LEAF_NODE = 2;</code>
   */
  NON_LEAF_NODE(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNKNOWN_LEAF_NODE = 0;</code>
   */
  public static final int UNKNOWN_LEAF_NODE_VALUE = 0;
  /**
   * <code>LEAF_NODE = 1;</code>
   */
  public static final int LEAF_NODE_VALUE = 1;
  /**
   * <code>NON_LEAF_NODE = 2;</code>
   */
  public static final int NON_LEAF_NODE_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static NodeTypeUiPbEnum valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static NodeTypeUiPbEnum forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN_LEAF_NODE;
      case 1: return LEAF_NODE;
      case 2: return NON_LEAF_NODE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<NodeTypeUiPbEnum>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      NodeTypeUiPbEnum> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<NodeTypeUiPbEnum>() {
          public NodeTypeUiPbEnum findValueByNumber(int number) {
            return NodeTypeUiPbEnum.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.tiwari.studence.proto.entity.EntityPbOuterClass.getDescriptor().getEnumTypes().get(1);
  }

  private static final NodeTypeUiPbEnum[] VALUES = values();

  public static NodeTypeUiPbEnum valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private NodeTypeUiPbEnum(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.tiwari.studence.proto.entity.NodeTypeUiPbEnum)
}

