// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: campusPb.proto

package com.tiwari.studence.proto.campus;

public interface OrganisationCreateAndCampusCreateReqPbOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.tiwari.studence.proto.campus.OrganisationCreateAndCampusCreateReqPb)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.tiwari.studence.proto.organisation.OrganisationPb organisation = 1;</code>
   * @return Whether the organisation field is set.
   */
  boolean hasOrganisation();
  /**
   * <code>.com.tiwari.studence.proto.organisation.OrganisationPb organisation = 1;</code>
   * @return The organisation.
   */
  com.tiwari.studence.proto.organisation.OrganisationPb getOrganisation();
  /**
   * <code>.com.tiwari.studence.proto.organisation.OrganisationPb organisation = 1;</code>
   */
  com.tiwari.studence.proto.organisation.OrganisationPbOrBuilder getOrganisationOrBuilder();

  /**
   * <code>.com.tiwari.studence.proto.campus.CampusPb campus = 2;</code>
   * @return Whether the campus field is set.
   */
  boolean hasCampus();
  /**
   * <code>.com.tiwari.studence.proto.campus.CampusPb campus = 2;</code>
   * @return The campus.
   */
  com.tiwari.studence.proto.campus.CampusPb getCampus();
  /**
   * <code>.com.tiwari.studence.proto.campus.CampusPb campus = 2;</code>
   */
  com.tiwari.studence.proto.campus.CampusPbOrBuilder getCampusOrBuilder();
}
