// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: requestContextPb.proto

package com.tiwari.studence.proto.requestcontext;

/**
 * Protobuf enum {@code com.tiwari.studence.proto.requestcontext.ReqPriorityUiEnum}
 */
public enum ReqPriorityUiEnum
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNKNOWN_REQ_PRIORITY = 0;</code>
   */
  UNKNOWN_REQ_PRIORITY(0),
  /**
   * <code>INSTANT = 1;</code>
   */
  INSTANT(1),
  /**
   * <code>BULK = 2;</code>
   */
  BULK(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNKNOWN_REQ_PRIORITY = 0;</code>
   */
  public static final int UNKNOWN_REQ_PRIORITY_VALUE = 0;
  /**
   * <code>INSTANT = 1;</code>
   */
  public static final int INSTANT_VALUE = 1;
  /**
   * <code>BULK = 2;</code>
   */
  public static final int BULK_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ReqPriorityUiEnum valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ReqPriorityUiEnum forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN_REQ_PRIORITY;
      case 1: return INSTANT;
      case 2: return BULK;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ReqPriorityUiEnum>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ReqPriorityUiEnum> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ReqPriorityUiEnum>() {
          public ReqPriorityUiEnum findValueByNumber(int number) {
            return ReqPriorityUiEnum.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.tiwari.studence.proto.requestcontext.RequestContextPbOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final ReqPriorityUiEnum[] VALUES = values();

  public static ReqPriorityUiEnum valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ReqPriorityUiEnum(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.tiwari.studence.proto.requestcontext.ReqPriorityUiEnum)
}

