// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: summaryPb.proto

package com.tiwari.studence.proto.summary;

public final class SummaryPbOuterClass {
  private SummaryPbOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tiwari_studence_proto_summary_SummaryPb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tiwari_studence_proto_summary_SummaryPb_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017summaryPb.proto\022!com.tiwari.studence.p" +
      "roto.summary\"4\n\tSummaryPb\022\024\n\014resultsCoun" +
      "t\030\001 \001(\005\022\021\n\tnextToken\030\002 \001(\tB\005P\001\240\001\001b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_tiwari_studence_proto_summary_SummaryPb_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_tiwari_studence_proto_summary_SummaryPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tiwari_studence_proto_summary_SummaryPb_descriptor,
        new java.lang.String[] { "ResultsCount", "NextToken", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
