// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: devicePb.proto

package com.tiwari.studence.proto.devices;

/**
 * Protobuf type {@code com.tiwari.studence.proto.devices.AndroidDisplayInfo}
 */
public final class AndroidDisplayInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.tiwari.studence.proto.devices.AndroidDisplayInfo)
    AndroidDisplayInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AndroidDisplayInfo.newBuilder() to construct.
  private AndroidDisplayInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AndroidDisplayInfo() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AndroidDisplayInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tiwari.studence.proto.devices.DevicePb.internal_static_com_tiwari_studence_proto_devices_AndroidDisplayInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tiwari.studence.proto.devices.DevicePb.internal_static_com_tiwari_studence_proto_devices_AndroidDisplayInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tiwari.studence.proto.devices.AndroidDisplayInfo.class, com.tiwari.studence.proto.devices.AndroidDisplayInfo.Builder.class);
  }

  public static final int DISPLAY_SIZE_INCHES_FIELD_NUMBER = 1;
  private float displaySizeInches_ = 0F;
  /**
   * <code>float display_size_inches = 1;</code>
   * @return The displaySizeInches.
   */
  @java.lang.Override
  public float getDisplaySizeInches() {
    return displaySizeInches_;
  }

  public static final int DISPLAY_WIDTH_PIXELS_FIELD_NUMBER = 2;
  private int displayWidthPixels_ = 0;
  /**
   * <code>int32 display_width_pixels = 2;</code>
   * @return The displayWidthPixels.
   */
  @java.lang.Override
  public int getDisplayWidthPixels() {
    return displayWidthPixels_;
  }

  public static final int DISPLAY_WIDTH_INCHES_FIELD_NUMBER = 3;
  private float displayWidthInches_ = 0F;
  /**
   * <code>float display_width_inches = 3;</code>
   * @return The displayWidthInches.
   */
  @java.lang.Override
  public float getDisplayWidthInches() {
    return displayWidthInches_;
  }

  public static final int DISPLAY_HEIGHT_PIXELS_FIELD_NUMBER = 4;
  private int displayHeightPixels_ = 0;
  /**
   * <code>int32 display_height_pixels = 4;</code>
   * @return The displayHeightPixels.
   */
  @java.lang.Override
  public int getDisplayHeightPixels() {
    return displayHeightPixels_;
  }

  public static final int DISPLAY_HEIGHT_INCHES_FIELD_NUMBER = 5;
  private float displayHeightInches_ = 0F;
  /**
   * <code>float display_height_inches = 5;</code>
   * @return The displayHeightInches.
   */
  @java.lang.Override
  public float getDisplayHeightInches() {
    return displayHeightInches_;
  }

  public static final int DISPLAY_X_DPI_FIELD_NUMBER = 6;
  private float displayXDpi_ = 0F;
  /**
   * <code>float display_x_dpi = 6;</code>
   * @return The displayXDpi.
   */
  @java.lang.Override
  public float getDisplayXDpi() {
    return displayXDpi_;
  }

  public static final int DISPLAY_Y_DPI_FIELD_NUMBER = 7;
  private float displayYDpi_ = 0F;
  /**
   * <code>float display_y_dpi = 7;</code>
   * @return The displayYDpi.
   */
  @java.lang.Override
  public float getDisplayYDpi() {
    return displayYDpi_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Float.floatToRawIntBits(displaySizeInches_) != 0) {
      output.writeFloat(1, displaySizeInches_);
    }
    if (displayWidthPixels_ != 0) {
      output.writeInt32(2, displayWidthPixels_);
    }
    if (java.lang.Float.floatToRawIntBits(displayWidthInches_) != 0) {
      output.writeFloat(3, displayWidthInches_);
    }
    if (displayHeightPixels_ != 0) {
      output.writeInt32(4, displayHeightPixels_);
    }
    if (java.lang.Float.floatToRawIntBits(displayHeightInches_) != 0) {
      output.writeFloat(5, displayHeightInches_);
    }
    if (java.lang.Float.floatToRawIntBits(displayXDpi_) != 0) {
      output.writeFloat(6, displayXDpi_);
    }
    if (java.lang.Float.floatToRawIntBits(displayYDpi_) != 0) {
      output.writeFloat(7, displayYDpi_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (java.lang.Float.floatToRawIntBits(displaySizeInches_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, displaySizeInches_);
    }
    if (displayWidthPixels_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, displayWidthPixels_);
    }
    if (java.lang.Float.floatToRawIntBits(displayWidthInches_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, displayWidthInches_);
    }
    if (displayHeightPixels_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, displayHeightPixels_);
    }
    if (java.lang.Float.floatToRawIntBits(displayHeightInches_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(5, displayHeightInches_);
    }
    if (java.lang.Float.floatToRawIntBits(displayXDpi_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(6, displayXDpi_);
    }
    if (java.lang.Float.floatToRawIntBits(displayYDpi_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(7, displayYDpi_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tiwari.studence.proto.devices.AndroidDisplayInfo)) {
      return super.equals(obj);
    }
    com.tiwari.studence.proto.devices.AndroidDisplayInfo other = (com.tiwari.studence.proto.devices.AndroidDisplayInfo) obj;

    if (java.lang.Float.floatToIntBits(getDisplaySizeInches())
        != java.lang.Float.floatToIntBits(
            other.getDisplaySizeInches())) return false;
    if (getDisplayWidthPixels()
        != other.getDisplayWidthPixels()) return false;
    if (java.lang.Float.floatToIntBits(getDisplayWidthInches())
        != java.lang.Float.floatToIntBits(
            other.getDisplayWidthInches())) return false;
    if (getDisplayHeightPixels()
        != other.getDisplayHeightPixels()) return false;
    if (java.lang.Float.floatToIntBits(getDisplayHeightInches())
        != java.lang.Float.floatToIntBits(
            other.getDisplayHeightInches())) return false;
    if (java.lang.Float.floatToIntBits(getDisplayXDpi())
        != java.lang.Float.floatToIntBits(
            other.getDisplayXDpi())) return false;
    if (java.lang.Float.floatToIntBits(getDisplayYDpi())
        != java.lang.Float.floatToIntBits(
            other.getDisplayYDpi())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DISPLAY_SIZE_INCHES_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getDisplaySizeInches());
    hash = (37 * hash) + DISPLAY_WIDTH_PIXELS_FIELD_NUMBER;
    hash = (53 * hash) + getDisplayWidthPixels();
    hash = (37 * hash) + DISPLAY_WIDTH_INCHES_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getDisplayWidthInches());
    hash = (37 * hash) + DISPLAY_HEIGHT_PIXELS_FIELD_NUMBER;
    hash = (53 * hash) + getDisplayHeightPixels();
    hash = (37 * hash) + DISPLAY_HEIGHT_INCHES_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getDisplayHeightInches());
    hash = (37 * hash) + DISPLAY_X_DPI_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getDisplayXDpi());
    hash = (37 * hash) + DISPLAY_Y_DPI_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getDisplayYDpi());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tiwari.studence.proto.devices.AndroidDisplayInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tiwari.studence.proto.devices.AndroidDisplayInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tiwari.studence.proto.devices.AndroidDisplayInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tiwari.studence.proto.devices.AndroidDisplayInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tiwari.studence.proto.devices.AndroidDisplayInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tiwari.studence.proto.devices.AndroidDisplayInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tiwari.studence.proto.devices.AndroidDisplayInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tiwari.studence.proto.devices.AndroidDisplayInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tiwari.studence.proto.devices.AndroidDisplayInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tiwari.studence.proto.devices.AndroidDisplayInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tiwari.studence.proto.devices.AndroidDisplayInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tiwari.studence.proto.devices.AndroidDisplayInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tiwari.studence.proto.devices.AndroidDisplayInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.tiwari.studence.proto.devices.AndroidDisplayInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.tiwari.studence.proto.devices.AndroidDisplayInfo)
      com.tiwari.studence.proto.devices.AndroidDisplayInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tiwari.studence.proto.devices.DevicePb.internal_static_com_tiwari_studence_proto_devices_AndroidDisplayInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tiwari.studence.proto.devices.DevicePb.internal_static_com_tiwari_studence_proto_devices_AndroidDisplayInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tiwari.studence.proto.devices.AndroidDisplayInfo.class, com.tiwari.studence.proto.devices.AndroidDisplayInfo.Builder.class);
    }

    // Construct using com.tiwari.studence.proto.devices.AndroidDisplayInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      displaySizeInches_ = 0F;
      displayWidthPixels_ = 0;
      displayWidthInches_ = 0F;
      displayHeightPixels_ = 0;
      displayHeightInches_ = 0F;
      displayXDpi_ = 0F;
      displayYDpi_ = 0F;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tiwari.studence.proto.devices.DevicePb.internal_static_com_tiwari_studence_proto_devices_AndroidDisplayInfo_descriptor;
    }

    @java.lang.Override
    public com.tiwari.studence.proto.devices.AndroidDisplayInfo getDefaultInstanceForType() {
      return com.tiwari.studence.proto.devices.AndroidDisplayInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.tiwari.studence.proto.devices.AndroidDisplayInfo build() {
      com.tiwari.studence.proto.devices.AndroidDisplayInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tiwari.studence.proto.devices.AndroidDisplayInfo buildPartial() {
      com.tiwari.studence.proto.devices.AndroidDisplayInfo result = new com.tiwari.studence.proto.devices.AndroidDisplayInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.tiwari.studence.proto.devices.AndroidDisplayInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.displaySizeInches_ = displaySizeInches_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.displayWidthPixels_ = displayWidthPixels_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.displayWidthInches_ = displayWidthInches_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.displayHeightPixels_ = displayHeightPixels_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.displayHeightInches_ = displayHeightInches_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.displayXDpi_ = displayXDpi_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.displayYDpi_ = displayYDpi_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tiwari.studence.proto.devices.AndroidDisplayInfo) {
        return mergeFrom((com.tiwari.studence.proto.devices.AndroidDisplayInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tiwari.studence.proto.devices.AndroidDisplayInfo other) {
      if (other == com.tiwari.studence.proto.devices.AndroidDisplayInfo.getDefaultInstance()) return this;
      if (other.getDisplaySizeInches() != 0F) {
        setDisplaySizeInches(other.getDisplaySizeInches());
      }
      if (other.getDisplayWidthPixels() != 0) {
        setDisplayWidthPixels(other.getDisplayWidthPixels());
      }
      if (other.getDisplayWidthInches() != 0F) {
        setDisplayWidthInches(other.getDisplayWidthInches());
      }
      if (other.getDisplayHeightPixels() != 0) {
        setDisplayHeightPixels(other.getDisplayHeightPixels());
      }
      if (other.getDisplayHeightInches() != 0F) {
        setDisplayHeightInches(other.getDisplayHeightInches());
      }
      if (other.getDisplayXDpi() != 0F) {
        setDisplayXDpi(other.getDisplayXDpi());
      }
      if (other.getDisplayYDpi() != 0F) {
        setDisplayYDpi(other.getDisplayYDpi());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {
              displaySizeInches_ = input.readFloat();
              bitField0_ |= 0x00000001;
              break;
            } // case 13
            case 16: {
              displayWidthPixels_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 29: {
              displayWidthInches_ = input.readFloat();
              bitField0_ |= 0x00000004;
              break;
            } // case 29
            case 32: {
              displayHeightPixels_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 45: {
              displayHeightInches_ = input.readFloat();
              bitField0_ |= 0x00000010;
              break;
            } // case 45
            case 53: {
              displayXDpi_ = input.readFloat();
              bitField0_ |= 0x00000020;
              break;
            } // case 53
            case 61: {
              displayYDpi_ = input.readFloat();
              bitField0_ |= 0x00000040;
              break;
            } // case 61
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private float displaySizeInches_ ;
    /**
     * <code>float display_size_inches = 1;</code>
     * @return The displaySizeInches.
     */
    @java.lang.Override
    public float getDisplaySizeInches() {
      return displaySizeInches_;
    }
    /**
     * <code>float display_size_inches = 1;</code>
     * @param value The displaySizeInches to set.
     * @return This builder for chaining.
     */
    public Builder setDisplaySizeInches(float value) {
      
      displaySizeInches_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>float display_size_inches = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDisplaySizeInches() {
      bitField0_ = (bitField0_ & ~0x00000001);
      displaySizeInches_ = 0F;
      onChanged();
      return this;
    }

    private int displayWidthPixels_ ;
    /**
     * <code>int32 display_width_pixels = 2;</code>
     * @return The displayWidthPixels.
     */
    @java.lang.Override
    public int getDisplayWidthPixels() {
      return displayWidthPixels_;
    }
    /**
     * <code>int32 display_width_pixels = 2;</code>
     * @param value The displayWidthPixels to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayWidthPixels(int value) {
      
      displayWidthPixels_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 display_width_pixels = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDisplayWidthPixels() {
      bitField0_ = (bitField0_ & ~0x00000002);
      displayWidthPixels_ = 0;
      onChanged();
      return this;
    }

    private float displayWidthInches_ ;
    /**
     * <code>float display_width_inches = 3;</code>
     * @return The displayWidthInches.
     */
    @java.lang.Override
    public float getDisplayWidthInches() {
      return displayWidthInches_;
    }
    /**
     * <code>float display_width_inches = 3;</code>
     * @param value The displayWidthInches to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayWidthInches(float value) {
      
      displayWidthInches_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>float display_width_inches = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDisplayWidthInches() {
      bitField0_ = (bitField0_ & ~0x00000004);
      displayWidthInches_ = 0F;
      onChanged();
      return this;
    }

    private int displayHeightPixels_ ;
    /**
     * <code>int32 display_height_pixels = 4;</code>
     * @return The displayHeightPixels.
     */
    @java.lang.Override
    public int getDisplayHeightPixels() {
      return displayHeightPixels_;
    }
    /**
     * <code>int32 display_height_pixels = 4;</code>
     * @param value The displayHeightPixels to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayHeightPixels(int value) {
      
      displayHeightPixels_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 display_height_pixels = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDisplayHeightPixels() {
      bitField0_ = (bitField0_ & ~0x00000008);
      displayHeightPixels_ = 0;
      onChanged();
      return this;
    }

    private float displayHeightInches_ ;
    /**
     * <code>float display_height_inches = 5;</code>
     * @return The displayHeightInches.
     */
    @java.lang.Override
    public float getDisplayHeightInches() {
      return displayHeightInches_;
    }
    /**
     * <code>float display_height_inches = 5;</code>
     * @param value The displayHeightInches to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayHeightInches(float value) {
      
      displayHeightInches_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>float display_height_inches = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDisplayHeightInches() {
      bitField0_ = (bitField0_ & ~0x00000010);
      displayHeightInches_ = 0F;
      onChanged();
      return this;
    }

    private float displayXDpi_ ;
    /**
     * <code>float display_x_dpi = 6;</code>
     * @return The displayXDpi.
     */
    @java.lang.Override
    public float getDisplayXDpi() {
      return displayXDpi_;
    }
    /**
     * <code>float display_x_dpi = 6;</code>
     * @param value The displayXDpi to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayXDpi(float value) {
      
      displayXDpi_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>float display_x_dpi = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearDisplayXDpi() {
      bitField0_ = (bitField0_ & ~0x00000020);
      displayXDpi_ = 0F;
      onChanged();
      return this;
    }

    private float displayYDpi_ ;
    /**
     * <code>float display_y_dpi = 7;</code>
     * @return The displayYDpi.
     */
    @java.lang.Override
    public float getDisplayYDpi() {
      return displayYDpi_;
    }
    /**
     * <code>float display_y_dpi = 7;</code>
     * @param value The displayYDpi to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayYDpi(float value) {
      
      displayYDpi_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>float display_y_dpi = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearDisplayYDpi() {
      bitField0_ = (bitField0_ & ~0x00000040);
      displayYDpi_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.tiwari.studence.proto.devices.AndroidDisplayInfo)
  }

  // @@protoc_insertion_point(class_scope:com.tiwari.studence.proto.devices.AndroidDisplayInfo)
  private static final com.tiwari.studence.proto.devices.AndroidDisplayInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tiwari.studence.proto.devices.AndroidDisplayInfo();
  }

  public static com.tiwari.studence.proto.devices.AndroidDisplayInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AndroidDisplayInfo>
      PARSER = new com.google.protobuf.AbstractParser<AndroidDisplayInfo>() {
    @java.lang.Override
    public AndroidDisplayInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AndroidDisplayInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AndroidDisplayInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tiwari.studence.proto.devices.AndroidDisplayInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

