// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: devicePb.proto

package com.tiwari.studence.proto.devices;

/**
 * Protobuf type {@code com.tiwari.studence.proto.devices.WebBrowserInfoDetails}
 */
public final class WebBrowserInfoDetails extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.tiwari.studence.proto.devices.WebBrowserInfoDetails)
    WebBrowserInfoDetailsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WebBrowserInfoDetails.newBuilder() to construct.
  private WebBrowserInfoDetails(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WebBrowserInfoDetails() {
    browserName_ = "";
    appCodeName_ = "";
    appName_ = "";
    appVersion_ = "";
    language_ = "";
    languages_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    platform_ = "";
    product_ = "";
    productSub_ = "";
    userAgent_ = "";
    vendor_ = "";
    vendorSub_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WebBrowserInfoDetails();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tiwari.studence.proto.devices.DevicePb.internal_static_com_tiwari_studence_proto_devices_WebBrowserInfoDetails_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tiwari.studence.proto.devices.DevicePb.internal_static_com_tiwari_studence_proto_devices_WebBrowserInfoDetails_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tiwari.studence.proto.devices.WebBrowserInfoDetails.class, com.tiwari.studence.proto.devices.WebBrowserInfoDetails.Builder.class);
  }

  public static final int BROWSERNAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object browserName_ = "";
  /**
   * <code>string browserName = 1;</code>
   * @return The browserName.
   */
  @java.lang.Override
  public java.lang.String getBrowserName() {
    java.lang.Object ref = browserName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      browserName_ = s;
      return s;
    }
  }
  /**
   * <code>string browserName = 1;</code>
   * @return The bytes for browserName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBrowserNameBytes() {
    java.lang.Object ref = browserName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      browserName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int APPCODENAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object appCodeName_ = "";
  /**
   * <code>string appCodeName = 2;</code>
   * @return The appCodeName.
   */
  @java.lang.Override
  public java.lang.String getAppCodeName() {
    java.lang.Object ref = appCodeName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      appCodeName_ = s;
      return s;
    }
  }
  /**
   * <code>string appCodeName = 2;</code>
   * @return The bytes for appCodeName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAppCodeNameBytes() {
    java.lang.Object ref = appCodeName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      appCodeName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int APPNAME_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object appName_ = "";
  /**
   * <code>string appName = 3;</code>
   * @return The appName.
   */
  @java.lang.Override
  public java.lang.String getAppName() {
    java.lang.Object ref = appName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      appName_ = s;
      return s;
    }
  }
  /**
   * <code>string appName = 3;</code>
   * @return The bytes for appName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAppNameBytes() {
    java.lang.Object ref = appName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      appName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int APPVERSION_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object appVersion_ = "";
  /**
   * <code>string appVersion = 4;</code>
   * @return The appVersion.
   */
  @java.lang.Override
  public java.lang.String getAppVersion() {
    java.lang.Object ref = appVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      appVersion_ = s;
      return s;
    }
  }
  /**
   * <code>string appVersion = 4;</code>
   * @return The bytes for appVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAppVersionBytes() {
    java.lang.Object ref = appVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      appVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICEMEMORY_FIELD_NUMBER = 5;
  private int deviceMemory_ = 0;
  /**
   * <code>uint32 deviceMemory = 5;</code>
   * @return The deviceMemory.
   */
  @java.lang.Override
  public int getDeviceMemory() {
    return deviceMemory_;
  }

  public static final int LANGUAGE_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object language_ = "";
  /**
   * <code>string language = 6;</code>
   * @return The language.
   */
  @java.lang.Override
  public java.lang.String getLanguage() {
    java.lang.Object ref = language_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      language_ = s;
      return s;
    }
  }
  /**
   * <code>string language = 6;</code>
   * @return The bytes for language.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLanguageBytes() {
    java.lang.Object ref = language_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      language_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LANGUAGES_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringList languages_;
  /**
   * <code>repeated string languages = 7;</code>
   * @return A list containing the languages.
   */
  public com.google.protobuf.ProtocolStringList
      getLanguagesList() {
    return languages_;
  }
  /**
   * <code>repeated string languages = 7;</code>
   * @return The count of languages.
   */
  public int getLanguagesCount() {
    return languages_.size();
  }
  /**
   * <code>repeated string languages = 7;</code>
   * @param index The index of the element to return.
   * @return The languages at the given index.
   */
  public java.lang.String getLanguages(int index) {
    return languages_.get(index);
  }
  /**
   * <code>repeated string languages = 7;</code>
   * @param index The index of the value to return.
   * @return The bytes of the languages at the given index.
   */
  public com.google.protobuf.ByteString
      getLanguagesBytes(int index) {
    return languages_.getByteString(index);
  }

  public static final int PLATFORM_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object platform_ = "";
  /**
   * <code>string platform = 8;</code>
   * @return The platform.
   */
  @java.lang.Override
  public java.lang.String getPlatform() {
    java.lang.Object ref = platform_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      platform_ = s;
      return s;
    }
  }
  /**
   * <code>string platform = 8;</code>
   * @return The bytes for platform.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPlatformBytes() {
    java.lang.Object ref = platform_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      platform_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRODUCT_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object product_ = "";
  /**
   * <code>string product = 9;</code>
   * @return The product.
   */
  @java.lang.Override
  public java.lang.String getProduct() {
    java.lang.Object ref = product_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      product_ = s;
      return s;
    }
  }
  /**
   * <code>string product = 9;</code>
   * @return The bytes for product.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProductBytes() {
    java.lang.Object ref = product_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      product_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRODUCTSUB_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object productSub_ = "";
  /**
   * <code>string productSub = 10;</code>
   * @return The productSub.
   */
  @java.lang.Override
  public java.lang.String getProductSub() {
    java.lang.Object ref = productSub_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      productSub_ = s;
      return s;
    }
  }
  /**
   * <code>string productSub = 10;</code>
   * @return The bytes for productSub.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProductSubBytes() {
    java.lang.Object ref = productSub_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      productSub_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERAGENT_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private volatile java.lang.Object userAgent_ = "";
  /**
   * <code>string userAgent = 11;</code>
   * @return The userAgent.
   */
  @java.lang.Override
  public java.lang.String getUserAgent() {
    java.lang.Object ref = userAgent_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userAgent_ = s;
      return s;
    }
  }
  /**
   * <code>string userAgent = 11;</code>
   * @return The bytes for userAgent.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserAgentBytes() {
    java.lang.Object ref = userAgent_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userAgent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VENDOR_FIELD_NUMBER = 12;
  @SuppressWarnings("serial")
  private volatile java.lang.Object vendor_ = "";
  /**
   * <code>string vendor = 12;</code>
   * @return The vendor.
   */
  @java.lang.Override
  public java.lang.String getVendor() {
    java.lang.Object ref = vendor_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      vendor_ = s;
      return s;
    }
  }
  /**
   * <code>string vendor = 12;</code>
   * @return The bytes for vendor.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVendorBytes() {
    java.lang.Object ref = vendor_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      vendor_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VENDORSUB_FIELD_NUMBER = 13;
  @SuppressWarnings("serial")
  private volatile java.lang.Object vendorSub_ = "";
  /**
   * <code>string vendorSub = 13;</code>
   * @return The vendorSub.
   */
  @java.lang.Override
  public java.lang.String getVendorSub() {
    java.lang.Object ref = vendorSub_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      vendorSub_ = s;
      return s;
    }
  }
  /**
   * <code>string vendorSub = 13;</code>
   * @return The bytes for vendorSub.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVendorSubBytes() {
    java.lang.Object ref = vendorSub_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      vendorSub_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HARDWARECONCURRENCY_FIELD_NUMBER = 14;
  private int hardwareConcurrency_ = 0;
  /**
   * <code>uint32 hardwareConcurrency = 14;</code>
   * @return The hardwareConcurrency.
   */
  @java.lang.Override
  public int getHardwareConcurrency() {
    return hardwareConcurrency_;
  }

  public static final int MAXTOUCHPOINTS_FIELD_NUMBER = 15;
  private int maxTouchPoints_ = 0;
  /**
   * <code>uint32 maxTouchPoints = 15;</code>
   * @return The maxTouchPoints.
   */
  @java.lang.Override
  public int getMaxTouchPoints() {
    return maxTouchPoints_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(browserName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, browserName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appCodeName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, appCodeName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, appName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appVersion_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, appVersion_);
    }
    if (deviceMemory_ != 0) {
      output.writeUInt32(5, deviceMemory_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(language_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, language_);
    }
    for (int i = 0; i < languages_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, languages_.getRaw(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(platform_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, platform_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(product_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, product_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productSub_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, productSub_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userAgent_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, userAgent_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(vendor_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, vendor_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(vendorSub_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, vendorSub_);
    }
    if (hardwareConcurrency_ != 0) {
      output.writeUInt32(14, hardwareConcurrency_);
    }
    if (maxTouchPoints_ != 0) {
      output.writeUInt32(15, maxTouchPoints_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(browserName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, browserName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appCodeName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, appCodeName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, appName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appVersion_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, appVersion_);
    }
    if (deviceMemory_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, deviceMemory_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(language_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, language_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < languages_.size(); i++) {
        dataSize += computeStringSizeNoTag(languages_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getLanguagesList().size();
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(platform_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, platform_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(product_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, product_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productSub_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, productSub_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userAgent_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, userAgent_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(vendor_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, vendor_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(vendorSub_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, vendorSub_);
    }
    if (hardwareConcurrency_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(14, hardwareConcurrency_);
    }
    if (maxTouchPoints_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(15, maxTouchPoints_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tiwari.studence.proto.devices.WebBrowserInfoDetails)) {
      return super.equals(obj);
    }
    com.tiwari.studence.proto.devices.WebBrowserInfoDetails other = (com.tiwari.studence.proto.devices.WebBrowserInfoDetails) obj;

    if (!getBrowserName()
        .equals(other.getBrowserName())) return false;
    if (!getAppCodeName()
        .equals(other.getAppCodeName())) return false;
    if (!getAppName()
        .equals(other.getAppName())) return false;
    if (!getAppVersion()
        .equals(other.getAppVersion())) return false;
    if (getDeviceMemory()
        != other.getDeviceMemory()) return false;
    if (!getLanguage()
        .equals(other.getLanguage())) return false;
    if (!getLanguagesList()
        .equals(other.getLanguagesList())) return false;
    if (!getPlatform()
        .equals(other.getPlatform())) return false;
    if (!getProduct()
        .equals(other.getProduct())) return false;
    if (!getProductSub()
        .equals(other.getProductSub())) return false;
    if (!getUserAgent()
        .equals(other.getUserAgent())) return false;
    if (!getVendor()
        .equals(other.getVendor())) return false;
    if (!getVendorSub()
        .equals(other.getVendorSub())) return false;
    if (getHardwareConcurrency()
        != other.getHardwareConcurrency()) return false;
    if (getMaxTouchPoints()
        != other.getMaxTouchPoints()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BROWSERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getBrowserName().hashCode();
    hash = (37 * hash) + APPCODENAME_FIELD_NUMBER;
    hash = (53 * hash) + getAppCodeName().hashCode();
    hash = (37 * hash) + APPNAME_FIELD_NUMBER;
    hash = (53 * hash) + getAppName().hashCode();
    hash = (37 * hash) + APPVERSION_FIELD_NUMBER;
    hash = (53 * hash) + getAppVersion().hashCode();
    hash = (37 * hash) + DEVICEMEMORY_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceMemory();
    hash = (37 * hash) + LANGUAGE_FIELD_NUMBER;
    hash = (53 * hash) + getLanguage().hashCode();
    if (getLanguagesCount() > 0) {
      hash = (37 * hash) + LANGUAGES_FIELD_NUMBER;
      hash = (53 * hash) + getLanguagesList().hashCode();
    }
    hash = (37 * hash) + PLATFORM_FIELD_NUMBER;
    hash = (53 * hash) + getPlatform().hashCode();
    hash = (37 * hash) + PRODUCT_FIELD_NUMBER;
    hash = (53 * hash) + getProduct().hashCode();
    hash = (37 * hash) + PRODUCTSUB_FIELD_NUMBER;
    hash = (53 * hash) + getProductSub().hashCode();
    hash = (37 * hash) + USERAGENT_FIELD_NUMBER;
    hash = (53 * hash) + getUserAgent().hashCode();
    hash = (37 * hash) + VENDOR_FIELD_NUMBER;
    hash = (53 * hash) + getVendor().hashCode();
    hash = (37 * hash) + VENDORSUB_FIELD_NUMBER;
    hash = (53 * hash) + getVendorSub().hashCode();
    hash = (37 * hash) + HARDWARECONCURRENCY_FIELD_NUMBER;
    hash = (53 * hash) + getHardwareConcurrency();
    hash = (37 * hash) + MAXTOUCHPOINTS_FIELD_NUMBER;
    hash = (53 * hash) + getMaxTouchPoints();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tiwari.studence.proto.devices.WebBrowserInfoDetails parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tiwari.studence.proto.devices.WebBrowserInfoDetails parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tiwari.studence.proto.devices.WebBrowserInfoDetails parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tiwari.studence.proto.devices.WebBrowserInfoDetails parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tiwari.studence.proto.devices.WebBrowserInfoDetails parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tiwari.studence.proto.devices.WebBrowserInfoDetails parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tiwari.studence.proto.devices.WebBrowserInfoDetails parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tiwari.studence.proto.devices.WebBrowserInfoDetails parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tiwari.studence.proto.devices.WebBrowserInfoDetails parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tiwari.studence.proto.devices.WebBrowserInfoDetails parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tiwari.studence.proto.devices.WebBrowserInfoDetails parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tiwari.studence.proto.devices.WebBrowserInfoDetails parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tiwari.studence.proto.devices.WebBrowserInfoDetails prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.tiwari.studence.proto.devices.WebBrowserInfoDetails}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.tiwari.studence.proto.devices.WebBrowserInfoDetails)
      com.tiwari.studence.proto.devices.WebBrowserInfoDetailsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tiwari.studence.proto.devices.DevicePb.internal_static_com_tiwari_studence_proto_devices_WebBrowserInfoDetails_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tiwari.studence.proto.devices.DevicePb.internal_static_com_tiwari_studence_proto_devices_WebBrowserInfoDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tiwari.studence.proto.devices.WebBrowserInfoDetails.class, com.tiwari.studence.proto.devices.WebBrowserInfoDetails.Builder.class);
    }

    // Construct using com.tiwari.studence.proto.devices.WebBrowserInfoDetails.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      browserName_ = "";
      appCodeName_ = "";
      appName_ = "";
      appVersion_ = "";
      deviceMemory_ = 0;
      language_ = "";
      languages_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000040);
      platform_ = "";
      product_ = "";
      productSub_ = "";
      userAgent_ = "";
      vendor_ = "";
      vendorSub_ = "";
      hardwareConcurrency_ = 0;
      maxTouchPoints_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tiwari.studence.proto.devices.DevicePb.internal_static_com_tiwari_studence_proto_devices_WebBrowserInfoDetails_descriptor;
    }

    @java.lang.Override
    public com.tiwari.studence.proto.devices.WebBrowserInfoDetails getDefaultInstanceForType() {
      return com.tiwari.studence.proto.devices.WebBrowserInfoDetails.getDefaultInstance();
    }

    @java.lang.Override
    public com.tiwari.studence.proto.devices.WebBrowserInfoDetails build() {
      com.tiwari.studence.proto.devices.WebBrowserInfoDetails result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tiwari.studence.proto.devices.WebBrowserInfoDetails buildPartial() {
      com.tiwari.studence.proto.devices.WebBrowserInfoDetails result = new com.tiwari.studence.proto.devices.WebBrowserInfoDetails(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.tiwari.studence.proto.devices.WebBrowserInfoDetails result) {
      if (((bitField0_ & 0x00000040) != 0)) {
        languages_ = languages_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000040);
      }
      result.languages_ = languages_;
    }

    private void buildPartial0(com.tiwari.studence.proto.devices.WebBrowserInfoDetails result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.browserName_ = browserName_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.appCodeName_ = appCodeName_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.appName_ = appName_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.appVersion_ = appVersion_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.deviceMemory_ = deviceMemory_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.language_ = language_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.platform_ = platform_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.product_ = product_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.productSub_ = productSub_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.userAgent_ = userAgent_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.vendor_ = vendor_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.vendorSub_ = vendorSub_;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.hardwareConcurrency_ = hardwareConcurrency_;
      }
      if (((from_bitField0_ & 0x00004000) != 0)) {
        result.maxTouchPoints_ = maxTouchPoints_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tiwari.studence.proto.devices.WebBrowserInfoDetails) {
        return mergeFrom((com.tiwari.studence.proto.devices.WebBrowserInfoDetails)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tiwari.studence.proto.devices.WebBrowserInfoDetails other) {
      if (other == com.tiwari.studence.proto.devices.WebBrowserInfoDetails.getDefaultInstance()) return this;
      if (!other.getBrowserName().isEmpty()) {
        browserName_ = other.browserName_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getAppCodeName().isEmpty()) {
        appCodeName_ = other.appCodeName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getAppName().isEmpty()) {
        appName_ = other.appName_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getAppVersion().isEmpty()) {
        appVersion_ = other.appVersion_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getDeviceMemory() != 0) {
        setDeviceMemory(other.getDeviceMemory());
      }
      if (!other.getLanguage().isEmpty()) {
        language_ = other.language_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.languages_.isEmpty()) {
        if (languages_.isEmpty()) {
          languages_ = other.languages_;
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          ensureLanguagesIsMutable();
          languages_.addAll(other.languages_);
        }
        onChanged();
      }
      if (!other.getPlatform().isEmpty()) {
        platform_ = other.platform_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getProduct().isEmpty()) {
        product_ = other.product_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (!other.getProductSub().isEmpty()) {
        productSub_ = other.productSub_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      if (!other.getUserAgent().isEmpty()) {
        userAgent_ = other.userAgent_;
        bitField0_ |= 0x00000400;
        onChanged();
      }
      if (!other.getVendor().isEmpty()) {
        vendor_ = other.vendor_;
        bitField0_ |= 0x00000800;
        onChanged();
      }
      if (!other.getVendorSub().isEmpty()) {
        vendorSub_ = other.vendorSub_;
        bitField0_ |= 0x00001000;
        onChanged();
      }
      if (other.getHardwareConcurrency() != 0) {
        setHardwareConcurrency(other.getHardwareConcurrency());
      }
      if (other.getMaxTouchPoints() != 0) {
        setMaxTouchPoints(other.getMaxTouchPoints());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              browserName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              appCodeName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              appName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              appVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              deviceMemory_ = input.readUInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              language_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureLanguagesIsMutable();
              languages_.add(s);
              break;
            } // case 58
            case 66: {
              platform_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              product_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              productSub_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 90: {
              userAgent_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            case 98: {
              vendor_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000800;
              break;
            } // case 98
            case 106: {
              vendorSub_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00001000;
              break;
            } // case 106
            case 112: {
              hardwareConcurrency_ = input.readUInt32();
              bitField0_ |= 0x00002000;
              break;
            } // case 112
            case 120: {
              maxTouchPoints_ = input.readUInt32();
              bitField0_ |= 0x00004000;
              break;
            } // case 120
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object browserName_ = "";
    /**
     * <code>string browserName = 1;</code>
     * @return The browserName.
     */
    public java.lang.String getBrowserName() {
      java.lang.Object ref = browserName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        browserName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string browserName = 1;</code>
     * @return The bytes for browserName.
     */
    public com.google.protobuf.ByteString
        getBrowserNameBytes() {
      java.lang.Object ref = browserName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        browserName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string browserName = 1;</code>
     * @param value The browserName to set.
     * @return This builder for chaining.
     */
    public Builder setBrowserName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      browserName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string browserName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBrowserName() {
      browserName_ = getDefaultInstance().getBrowserName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string browserName = 1;</code>
     * @param value The bytes for browserName to set.
     * @return This builder for chaining.
     */
    public Builder setBrowserNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      browserName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object appCodeName_ = "";
    /**
     * <code>string appCodeName = 2;</code>
     * @return The appCodeName.
     */
    public java.lang.String getAppCodeName() {
      java.lang.Object ref = appCodeName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appCodeName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string appCodeName = 2;</code>
     * @return The bytes for appCodeName.
     */
    public com.google.protobuf.ByteString
        getAppCodeNameBytes() {
      java.lang.Object ref = appCodeName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appCodeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string appCodeName = 2;</code>
     * @param value The appCodeName to set.
     * @return This builder for chaining.
     */
    public Builder setAppCodeName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      appCodeName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string appCodeName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppCodeName() {
      appCodeName_ = getDefaultInstance().getAppCodeName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string appCodeName = 2;</code>
     * @param value The bytes for appCodeName to set.
     * @return This builder for chaining.
     */
    public Builder setAppCodeNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      appCodeName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object appName_ = "";
    /**
     * <code>string appName = 3;</code>
     * @return The appName.
     */
    public java.lang.String getAppName() {
      java.lang.Object ref = appName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string appName = 3;</code>
     * @return The bytes for appName.
     */
    public com.google.protobuf.ByteString
        getAppNameBytes() {
      java.lang.Object ref = appName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string appName = 3;</code>
     * @param value The appName to set.
     * @return This builder for chaining.
     */
    public Builder setAppName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      appName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string appName = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppName() {
      appName_ = getDefaultInstance().getAppName();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string appName = 3;</code>
     * @param value The bytes for appName to set.
     * @return This builder for chaining.
     */
    public Builder setAppNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      appName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object appVersion_ = "";
    /**
     * <code>string appVersion = 4;</code>
     * @return The appVersion.
     */
    public java.lang.String getAppVersion() {
      java.lang.Object ref = appVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string appVersion = 4;</code>
     * @return The bytes for appVersion.
     */
    public com.google.protobuf.ByteString
        getAppVersionBytes() {
      java.lang.Object ref = appVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string appVersion = 4;</code>
     * @param value The appVersion to set.
     * @return This builder for chaining.
     */
    public Builder setAppVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      appVersion_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string appVersion = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppVersion() {
      appVersion_ = getDefaultInstance().getAppVersion();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string appVersion = 4;</code>
     * @param value The bytes for appVersion to set.
     * @return This builder for chaining.
     */
    public Builder setAppVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      appVersion_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private int deviceMemory_ ;
    /**
     * <code>uint32 deviceMemory = 5;</code>
     * @return The deviceMemory.
     */
    @java.lang.Override
    public int getDeviceMemory() {
      return deviceMemory_;
    }
    /**
     * <code>uint32 deviceMemory = 5;</code>
     * @param value The deviceMemory to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceMemory(int value) {
      
      deviceMemory_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 deviceMemory = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceMemory() {
      bitField0_ = (bitField0_ & ~0x00000010);
      deviceMemory_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object language_ = "";
    /**
     * <code>string language = 6;</code>
     * @return The language.
     */
    public java.lang.String getLanguage() {
      java.lang.Object ref = language_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        language_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string language = 6;</code>
     * @return The bytes for language.
     */
    public com.google.protobuf.ByteString
        getLanguageBytes() {
      java.lang.Object ref = language_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        language_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string language = 6;</code>
     * @param value The language to set.
     * @return This builder for chaining.
     */
    public Builder setLanguage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      language_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string language = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearLanguage() {
      language_ = getDefaultInstance().getLanguage();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string language = 6;</code>
     * @param value The bytes for language to set.
     * @return This builder for chaining.
     */
    public Builder setLanguageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      language_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList languages_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureLanguagesIsMutable() {
      if (!((bitField0_ & 0x00000040) != 0)) {
        languages_ = new com.google.protobuf.LazyStringArrayList(languages_);
        bitField0_ |= 0x00000040;
       }
    }
    /**
     * <code>repeated string languages = 7;</code>
     * @return A list containing the languages.
     */
    public com.google.protobuf.ProtocolStringList
        getLanguagesList() {
      return languages_.getUnmodifiableView();
    }
    /**
     * <code>repeated string languages = 7;</code>
     * @return The count of languages.
     */
    public int getLanguagesCount() {
      return languages_.size();
    }
    /**
     * <code>repeated string languages = 7;</code>
     * @param index The index of the element to return.
     * @return The languages at the given index.
     */
    public java.lang.String getLanguages(int index) {
      return languages_.get(index);
    }
    /**
     * <code>repeated string languages = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the languages at the given index.
     */
    public com.google.protobuf.ByteString
        getLanguagesBytes(int index) {
      return languages_.getByteString(index);
    }
    /**
     * <code>repeated string languages = 7;</code>
     * @param index The index to set the value at.
     * @param value The languages to set.
     * @return This builder for chaining.
     */
    public Builder setLanguages(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureLanguagesIsMutable();
      languages_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string languages = 7;</code>
     * @param value The languages to add.
     * @return This builder for chaining.
     */
    public Builder addLanguages(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureLanguagesIsMutable();
      languages_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string languages = 7;</code>
     * @param values The languages to add.
     * @return This builder for chaining.
     */
    public Builder addAllLanguages(
        java.lang.Iterable<java.lang.String> values) {
      ensureLanguagesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, languages_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string languages = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearLanguages() {
      languages_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string languages = 7;</code>
     * @param value The bytes of the languages to add.
     * @return This builder for chaining.
     */
    public Builder addLanguagesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureLanguagesIsMutable();
      languages_.add(value);
      onChanged();
      return this;
    }

    private java.lang.Object platform_ = "";
    /**
     * <code>string platform = 8;</code>
     * @return The platform.
     */
    public java.lang.String getPlatform() {
      java.lang.Object ref = platform_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        platform_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string platform = 8;</code>
     * @return The bytes for platform.
     */
    public com.google.protobuf.ByteString
        getPlatformBytes() {
      java.lang.Object ref = platform_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        platform_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string platform = 8;</code>
     * @param value The platform to set.
     * @return This builder for chaining.
     */
    public Builder setPlatform(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      platform_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string platform = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlatform() {
      platform_ = getDefaultInstance().getPlatform();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string platform = 8;</code>
     * @param value The bytes for platform to set.
     * @return This builder for chaining.
     */
    public Builder setPlatformBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      platform_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private java.lang.Object product_ = "";
    /**
     * <code>string product = 9;</code>
     * @return The product.
     */
    public java.lang.String getProduct() {
      java.lang.Object ref = product_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        product_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string product = 9;</code>
     * @return The bytes for product.
     */
    public com.google.protobuf.ByteString
        getProductBytes() {
      java.lang.Object ref = product_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        product_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string product = 9;</code>
     * @param value The product to set.
     * @return This builder for chaining.
     */
    public Builder setProduct(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      product_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>string product = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearProduct() {
      product_ = getDefaultInstance().getProduct();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>string product = 9;</code>
     * @param value The bytes for product to set.
     * @return This builder for chaining.
     */
    public Builder setProductBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      product_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private java.lang.Object productSub_ = "";
    /**
     * <code>string productSub = 10;</code>
     * @return The productSub.
     */
    public java.lang.String getProductSub() {
      java.lang.Object ref = productSub_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productSub_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string productSub = 10;</code>
     * @return The bytes for productSub.
     */
    public com.google.protobuf.ByteString
        getProductSubBytes() {
      java.lang.Object ref = productSub_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productSub_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string productSub = 10;</code>
     * @param value The productSub to set.
     * @return This builder for chaining.
     */
    public Builder setProductSub(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      productSub_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>string productSub = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductSub() {
      productSub_ = getDefaultInstance().getProductSub();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <code>string productSub = 10;</code>
     * @param value The bytes for productSub to set.
     * @return This builder for chaining.
     */
    public Builder setProductSubBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      productSub_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    private java.lang.Object userAgent_ = "";
    /**
     * <code>string userAgent = 11;</code>
     * @return The userAgent.
     */
    public java.lang.String getUserAgent() {
      java.lang.Object ref = userAgent_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userAgent_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string userAgent = 11;</code>
     * @return The bytes for userAgent.
     */
    public com.google.protobuf.ByteString
        getUserAgentBytes() {
      java.lang.Object ref = userAgent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userAgent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userAgent = 11;</code>
     * @param value The userAgent to set.
     * @return This builder for chaining.
     */
    public Builder setUserAgent(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      userAgent_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>string userAgent = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserAgent() {
      userAgent_ = getDefaultInstance().getUserAgent();
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }
    /**
     * <code>string userAgent = 11;</code>
     * @param value The bytes for userAgent to set.
     * @return This builder for chaining.
     */
    public Builder setUserAgentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      userAgent_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }

    private java.lang.Object vendor_ = "";
    /**
     * <code>string vendor = 12;</code>
     * @return The vendor.
     */
    public java.lang.String getVendor() {
      java.lang.Object ref = vendor_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        vendor_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string vendor = 12;</code>
     * @return The bytes for vendor.
     */
    public com.google.protobuf.ByteString
        getVendorBytes() {
      java.lang.Object ref = vendor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vendor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string vendor = 12;</code>
     * @param value The vendor to set.
     * @return This builder for chaining.
     */
    public Builder setVendor(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      vendor_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>string vendor = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearVendor() {
      vendor_ = getDefaultInstance().getVendor();
      bitField0_ = (bitField0_ & ~0x00000800);
      onChanged();
      return this;
    }
    /**
     * <code>string vendor = 12;</code>
     * @param value The bytes for vendor to set.
     * @return This builder for chaining.
     */
    public Builder setVendorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      vendor_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }

    private java.lang.Object vendorSub_ = "";
    /**
     * <code>string vendorSub = 13;</code>
     * @return The vendorSub.
     */
    public java.lang.String getVendorSub() {
      java.lang.Object ref = vendorSub_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        vendorSub_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string vendorSub = 13;</code>
     * @return The bytes for vendorSub.
     */
    public com.google.protobuf.ByteString
        getVendorSubBytes() {
      java.lang.Object ref = vendorSub_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vendorSub_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string vendorSub = 13;</code>
     * @param value The vendorSub to set.
     * @return This builder for chaining.
     */
    public Builder setVendorSub(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      vendorSub_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>string vendorSub = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearVendorSub() {
      vendorSub_ = getDefaultInstance().getVendorSub();
      bitField0_ = (bitField0_ & ~0x00001000);
      onChanged();
      return this;
    }
    /**
     * <code>string vendorSub = 13;</code>
     * @param value The bytes for vendorSub to set.
     * @return This builder for chaining.
     */
    public Builder setVendorSubBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      vendorSub_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }

    private int hardwareConcurrency_ ;
    /**
     * <code>uint32 hardwareConcurrency = 14;</code>
     * @return The hardwareConcurrency.
     */
    @java.lang.Override
    public int getHardwareConcurrency() {
      return hardwareConcurrency_;
    }
    /**
     * <code>uint32 hardwareConcurrency = 14;</code>
     * @param value The hardwareConcurrency to set.
     * @return This builder for chaining.
     */
    public Builder setHardwareConcurrency(int value) {
      
      hardwareConcurrency_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 hardwareConcurrency = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearHardwareConcurrency() {
      bitField0_ = (bitField0_ & ~0x00002000);
      hardwareConcurrency_ = 0;
      onChanged();
      return this;
    }

    private int maxTouchPoints_ ;
    /**
     * <code>uint32 maxTouchPoints = 15;</code>
     * @return The maxTouchPoints.
     */
    @java.lang.Override
    public int getMaxTouchPoints() {
      return maxTouchPoints_;
    }
    /**
     * <code>uint32 maxTouchPoints = 15;</code>
     * @param value The maxTouchPoints to set.
     * @return This builder for chaining.
     */
    public Builder setMaxTouchPoints(int value) {
      
      maxTouchPoints_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 maxTouchPoints = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxTouchPoints() {
      bitField0_ = (bitField0_ & ~0x00004000);
      maxTouchPoints_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.tiwari.studence.proto.devices.WebBrowserInfoDetails)
  }

  // @@protoc_insertion_point(class_scope:com.tiwari.studence.proto.devices.WebBrowserInfoDetails)
  private static final com.tiwari.studence.proto.devices.WebBrowserInfoDetails DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tiwari.studence.proto.devices.WebBrowserInfoDetails();
  }

  public static com.tiwari.studence.proto.devices.WebBrowserInfoDetails getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WebBrowserInfoDetails>
      PARSER = new com.google.protobuf.AbstractParser<WebBrowserInfoDetails>() {
    @java.lang.Override
    public WebBrowserInfoDetails parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<WebBrowserInfoDetails> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WebBrowserInfoDetails> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tiwari.studence.proto.devices.WebBrowserInfoDetails getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

