// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: error.proto

package com.tiwari.studence.proto.error;

public interface ErrorProtoPbOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.tiwari.studence.proto.error.ErrorProtoPb)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.tiwari.studence.proto.error.ErrorTypePbEnum ErrorTypePbEnum = 1;</code>
   * @return The enum numeric value on the wire for errorTypePbEnum.
   */
  int getErrorTypePbEnumValue();
  /**
   * <code>.com.tiwari.studence.proto.error.ErrorTypePbEnum ErrorTypePbEnum = 1;</code>
   * @return The errorTypePbEnum.
   */
  com.tiwari.studence.proto.error.ErrorTypePbEnum getErrorTypePbEnum();

  /**
   * <pre>
   * id less useful for logs
   * </pre>
   *
   * <code>string errorEnumClass = 2;</code>
   * @return The errorEnumClass.
   */
  java.lang.String getErrorEnumClass();
  /**
   * <pre>
   * id less useful for logs
   * </pre>
   *
   * <code>string errorEnumClass = 2;</code>
   * @return The bytes for errorEnumClass.
   */
  com.google.protobuf.ByteString
      getErrorEnumClassBytes();

  /**
   * <pre>
   * id less useful for logs
   * </pre>
   *
   * <code>string errorEnumValue = 3;</code>
   * @return The errorEnumValue.
   */
  java.lang.String getErrorEnumValue();
  /**
   * <pre>
   * id less useful for logs
   * </pre>
   *
   * <code>string errorEnumValue = 3;</code>
   * @return The bytes for errorEnumValue.
   */
  com.google.protobuf.ByteString
      getErrorEnumValueBytes();

  /**
   * <pre>
   * protobinary/json/prototext string. prototext is default.
   * </pre>
   *
   * <code>string errorData = 4;</code>
   * @return The errorData.
   */
  java.lang.String getErrorData();
  /**
   * <pre>
   * protobinary/json/prototext string. prototext is default.
   * </pre>
   *
   * <code>string errorData = 4;</code>
   * @return The bytes for errorData.
   */
  com.google.protobuf.ByteString
      getErrorDataBytes();

  /**
   * <code>repeated string serviceId = 5;</code>
   * @return A list containing the serviceId.
   */
  java.util.List<java.lang.String>
      getServiceIdList();
  /**
   * <code>repeated string serviceId = 5;</code>
   * @return The count of serviceId.
   */
  int getServiceIdCount();
  /**
   * <code>repeated string serviceId = 5;</code>
   * @param index The index of the element to return.
   * @return The serviceId at the given index.
   */
  java.lang.String getServiceId(int index);
  /**
   * <code>repeated string serviceId = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the serviceId at the given index.
   */
  com.google.protobuf.ByteString
      getServiceIdBytes(int index);

  /**
   * <pre>
   * Full class name of error data
   * </pre>
   *
   * <code>string errorDataClass = 6;</code>
   * @return The errorDataClass.
   */
  java.lang.String getErrorDataClass();
  /**
   * <pre>
   * Full class name of error data
   * </pre>
   *
   * <code>string errorDataClass = 6;</code>
   * @return The bytes for errorDataClass.
   */
  com.google.protobuf.ByteString
      getErrorDataClassBytes();

  /**
   * <code>.com.tiwari.studence.proto.error.ErrorCategoryUiEnum errorCategory = 7;</code>
   * @return The enum numeric value on the wire for errorCategory.
   */
  int getErrorCategoryValue();
  /**
   * <code>.com.tiwari.studence.proto.error.ErrorCategoryUiEnum errorCategory = 7;</code>
   * @return The errorCategory.
   */
  com.tiwari.studence.proto.error.ErrorCategoryUiEnum getErrorCategory();
}
