// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: devicePb.proto

package com.tiwari.studence.proto.devices;

public interface AndroidDisplayInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.tiwari.studence.proto.devices.AndroidDisplayInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float display_size_inches = 1;</code>
   * @return The displaySizeInches.
   */
  float getDisplaySizeInches();

  /**
   * <code>int32 display_width_pixels = 2;</code>
   * @return The displayWidthPixels.
   */
  int getDisplayWidthPixels();

  /**
   * <code>float display_width_inches = 3;</code>
   * @return The displayWidthInches.
   */
  float getDisplayWidthInches();

  /**
   * <code>int32 display_height_pixels = 4;</code>
   * @return The displayHeightPixels.
   */
  int getDisplayHeightPixels();

  /**
   * <code>float display_height_inches = 5;</code>
   * @return The displayHeightInches.
   */
  float getDisplayHeightInches();

  /**
   * <code>float display_x_dpi = 6;</code>
   * @return The displayXDpi.
   */
  float getDisplayXDpi();

  /**
   * <code>float display_y_dpi = 7;</code>
   * @return The displayYDpi.
   */
  float getDisplayYDpi();
}
