// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: match.proto

package com.tiwari.studence.proto.match;

/**
 * Protobuf type {@code com.tiwari.studence.proto.match.MatchInfoPb}
 */
public final class MatchInfoPb extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.tiwari.studence.proto.match.MatchInfoPb)
    MatchInfoPbOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MatchInfoPb.newBuilder() to construct.
  private MatchInfoPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MatchInfoPb() {
    sourceRefId_ = "";
    matchInfo_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MatchInfoPb();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tiwari.studence.proto.match.Match.internal_static_com_tiwari_studence_proto_match_MatchInfoPb_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tiwari.studence.proto.match.Match.internal_static_com_tiwari_studence_proto_match_MatchInfoPb_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tiwari.studence.proto.match.MatchInfoPb.class, com.tiwari.studence.proto.match.MatchInfoPb.Builder.class);
  }

  private int bitField0_;
  public static final int SOURCEREFID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sourceRefId_ = "";
  /**
   * <code>optional string sourceRefId = 1;</code>
   * @return Whether the sourceRefId field is set.
   */
  @java.lang.Override
  public boolean hasSourceRefId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string sourceRefId = 1;</code>
   * @return The sourceRefId.
   */
  @java.lang.Override
  public java.lang.String getSourceRefId() {
    java.lang.Object ref = sourceRefId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceRefId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string sourceRefId = 1;</code>
   * @return The bytes for sourceRefId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceRefIdBytes() {
    java.lang.Object ref = sourceRefId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceRefId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MATCHINFO_FIELD_NUMBER = 2;
  private int matchInfo_ = 0;
  /**
   * <code>optional .com.tiwari.studence.proto.match.MatchInfoUiEnum matchInfo = 2;</code>
   * @return Whether the matchInfo field is set.
   */
  @java.lang.Override public boolean hasMatchInfo() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .com.tiwari.studence.proto.match.MatchInfoUiEnum matchInfo = 2;</code>
   * @return The enum numeric value on the wire for matchInfo.
   */
  @java.lang.Override public int getMatchInfoValue() {
    return matchInfo_;
  }
  /**
   * <code>optional .com.tiwari.studence.proto.match.MatchInfoUiEnum matchInfo = 2;</code>
   * @return The matchInfo.
   */
  @java.lang.Override public com.tiwari.studence.proto.match.MatchInfoUiEnum getMatchInfo() {
    com.tiwari.studence.proto.match.MatchInfoUiEnum result = com.tiwari.studence.proto.match.MatchInfoUiEnum.forNumber(matchInfo_);
    return result == null ? com.tiwari.studence.proto.match.MatchInfoUiEnum.UNRECOGNIZED : result;
  }

  public static final int MATCHEDTIME_FIELD_NUMBER = 3;
  private com.tiwari.studence.proto.time.TimePb matchedTime_;
  /**
   * <code>optional .com.tiwari.studence.proto.time.TimePb matchedTime = 3;</code>
   * @return Whether the matchedTime field is set.
   */
  @java.lang.Override
  public boolean hasMatchedTime() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional .com.tiwari.studence.proto.time.TimePb matchedTime = 3;</code>
   * @return The matchedTime.
   */
  @java.lang.Override
  public com.tiwari.studence.proto.time.TimePb getMatchedTime() {
    return matchedTime_ == null ? com.tiwari.studence.proto.time.TimePb.getDefaultInstance() : matchedTime_;
  }
  /**
   * <code>optional .com.tiwari.studence.proto.time.TimePb matchedTime = 3;</code>
   */
  @java.lang.Override
  public com.tiwari.studence.proto.time.TimePbOrBuilder getMatchedTimeOrBuilder() {
    return matchedTime_ == null ? com.tiwari.studence.proto.time.TimePb.getDefaultInstance() : matchedTime_;
  }

  public static final int DIFF_FIELD_NUMBER = 4;
  private int diff_ = 0;
  /**
   * <code>optional int32 diff = 4;</code>
   * @return Whether the diff field is set.
   */
  @java.lang.Override
  public boolean hasDiff() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional int32 diff = 4;</code>
   * @return The diff.
   */
  @java.lang.Override
  public int getDiff() {
    return diff_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sourceRefId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeEnum(2, matchInfo_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(3, getMatchedTime());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeInt32(4, diff_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sourceRefId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, matchInfo_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getMatchedTime());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, diff_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tiwari.studence.proto.match.MatchInfoPb)) {
      return super.equals(obj);
    }
    com.tiwari.studence.proto.match.MatchInfoPb other = (com.tiwari.studence.proto.match.MatchInfoPb) obj;

    if (hasSourceRefId() != other.hasSourceRefId()) return false;
    if (hasSourceRefId()) {
      if (!getSourceRefId()
          .equals(other.getSourceRefId())) return false;
    }
    if (hasMatchInfo() != other.hasMatchInfo()) return false;
    if (hasMatchInfo()) {
      if (matchInfo_ != other.matchInfo_) return false;
    }
    if (hasMatchedTime() != other.hasMatchedTime()) return false;
    if (hasMatchedTime()) {
      if (!getMatchedTime()
          .equals(other.getMatchedTime())) return false;
    }
    if (hasDiff() != other.hasDiff()) return false;
    if (hasDiff()) {
      if (getDiff()
          != other.getDiff()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSourceRefId()) {
      hash = (37 * hash) + SOURCEREFID_FIELD_NUMBER;
      hash = (53 * hash) + getSourceRefId().hashCode();
    }
    if (hasMatchInfo()) {
      hash = (37 * hash) + MATCHINFO_FIELD_NUMBER;
      hash = (53 * hash) + matchInfo_;
    }
    if (hasMatchedTime()) {
      hash = (37 * hash) + MATCHEDTIME_FIELD_NUMBER;
      hash = (53 * hash) + getMatchedTime().hashCode();
    }
    if (hasDiff()) {
      hash = (37 * hash) + DIFF_FIELD_NUMBER;
      hash = (53 * hash) + getDiff();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tiwari.studence.proto.match.MatchInfoPb parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tiwari.studence.proto.match.MatchInfoPb parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tiwari.studence.proto.match.MatchInfoPb parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tiwari.studence.proto.match.MatchInfoPb parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tiwari.studence.proto.match.MatchInfoPb parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tiwari.studence.proto.match.MatchInfoPb parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tiwari.studence.proto.match.MatchInfoPb parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tiwari.studence.proto.match.MatchInfoPb parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tiwari.studence.proto.match.MatchInfoPb parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tiwari.studence.proto.match.MatchInfoPb parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tiwari.studence.proto.match.MatchInfoPb parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tiwari.studence.proto.match.MatchInfoPb parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tiwari.studence.proto.match.MatchInfoPb prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.tiwari.studence.proto.match.MatchInfoPb}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.tiwari.studence.proto.match.MatchInfoPb)
      com.tiwari.studence.proto.match.MatchInfoPbOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tiwari.studence.proto.match.Match.internal_static_com_tiwari_studence_proto_match_MatchInfoPb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tiwari.studence.proto.match.Match.internal_static_com_tiwari_studence_proto_match_MatchInfoPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tiwari.studence.proto.match.MatchInfoPb.class, com.tiwari.studence.proto.match.MatchInfoPb.Builder.class);
    }

    // Construct using com.tiwari.studence.proto.match.MatchInfoPb.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMatchedTimeFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sourceRefId_ = "";
      matchInfo_ = 0;
      matchedTime_ = null;
      if (matchedTimeBuilder_ != null) {
        matchedTimeBuilder_.dispose();
        matchedTimeBuilder_ = null;
      }
      diff_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tiwari.studence.proto.match.Match.internal_static_com_tiwari_studence_proto_match_MatchInfoPb_descriptor;
    }

    @java.lang.Override
    public com.tiwari.studence.proto.match.MatchInfoPb getDefaultInstanceForType() {
      return com.tiwari.studence.proto.match.MatchInfoPb.getDefaultInstance();
    }

    @java.lang.Override
    public com.tiwari.studence.proto.match.MatchInfoPb build() {
      com.tiwari.studence.proto.match.MatchInfoPb result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tiwari.studence.proto.match.MatchInfoPb buildPartial() {
      com.tiwari.studence.proto.match.MatchInfoPb result = new com.tiwari.studence.proto.match.MatchInfoPb(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.tiwari.studence.proto.match.MatchInfoPb result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sourceRefId_ = sourceRefId_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.matchInfo_ = matchInfo_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.matchedTime_ = matchedTimeBuilder_ == null
            ? matchedTime_
            : matchedTimeBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.diff_ = diff_;
        to_bitField0_ |= 0x00000008;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tiwari.studence.proto.match.MatchInfoPb) {
        return mergeFrom((com.tiwari.studence.proto.match.MatchInfoPb)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tiwari.studence.proto.match.MatchInfoPb other) {
      if (other == com.tiwari.studence.proto.match.MatchInfoPb.getDefaultInstance()) return this;
      if (other.hasSourceRefId()) {
        sourceRefId_ = other.sourceRefId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasMatchInfo()) {
        setMatchInfo(other.getMatchInfo());
      }
      if (other.hasMatchedTime()) {
        mergeMatchedTime(other.getMatchedTime());
      }
      if (other.hasDiff()) {
        setDiff(other.getDiff());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              sourceRefId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              matchInfo_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              input.readMessage(
                  getMatchedTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              diff_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object sourceRefId_ = "";
    /**
     * <code>optional string sourceRefId = 1;</code>
     * @return Whether the sourceRefId field is set.
     */
    public boolean hasSourceRefId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string sourceRefId = 1;</code>
     * @return The sourceRefId.
     */
    public java.lang.String getSourceRefId() {
      java.lang.Object ref = sourceRefId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceRefId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string sourceRefId = 1;</code>
     * @return The bytes for sourceRefId.
     */
    public com.google.protobuf.ByteString
        getSourceRefIdBytes() {
      java.lang.Object ref = sourceRefId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceRefId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string sourceRefId = 1;</code>
     * @param value The sourceRefId to set.
     * @return This builder for chaining.
     */
    public Builder setSourceRefId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sourceRefId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional string sourceRefId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceRefId() {
      sourceRefId_ = getDefaultInstance().getSourceRefId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>optional string sourceRefId = 1;</code>
     * @param value The bytes for sourceRefId to set.
     * @return This builder for chaining.
     */
    public Builder setSourceRefIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sourceRefId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int matchInfo_ = 0;
    /**
     * <code>optional .com.tiwari.studence.proto.match.MatchInfoUiEnum matchInfo = 2;</code>
     * @return Whether the matchInfo field is set.
     */
    @java.lang.Override public boolean hasMatchInfo() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .com.tiwari.studence.proto.match.MatchInfoUiEnum matchInfo = 2;</code>
     * @return The enum numeric value on the wire for matchInfo.
     */
    @java.lang.Override public int getMatchInfoValue() {
      return matchInfo_;
    }
    /**
     * <code>optional .com.tiwari.studence.proto.match.MatchInfoUiEnum matchInfo = 2;</code>
     * @param value The enum numeric value on the wire for matchInfo to set.
     * @return This builder for chaining.
     */
    public Builder setMatchInfoValue(int value) {
      matchInfo_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional .com.tiwari.studence.proto.match.MatchInfoUiEnum matchInfo = 2;</code>
     * @return The matchInfo.
     */
    @java.lang.Override
    public com.tiwari.studence.proto.match.MatchInfoUiEnum getMatchInfo() {
      com.tiwari.studence.proto.match.MatchInfoUiEnum result = com.tiwari.studence.proto.match.MatchInfoUiEnum.forNumber(matchInfo_);
      return result == null ? com.tiwari.studence.proto.match.MatchInfoUiEnum.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .com.tiwari.studence.proto.match.MatchInfoUiEnum matchInfo = 2;</code>
     * @param value The matchInfo to set.
     * @return This builder for chaining.
     */
    public Builder setMatchInfo(com.tiwari.studence.proto.match.MatchInfoUiEnum value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      matchInfo_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .com.tiwari.studence.proto.match.MatchInfoUiEnum matchInfo = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMatchInfo() {
      bitField0_ = (bitField0_ & ~0x00000002);
      matchInfo_ = 0;
      onChanged();
      return this;
    }

    private com.tiwari.studence.proto.time.TimePb matchedTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tiwari.studence.proto.time.TimePb, com.tiwari.studence.proto.time.TimePb.Builder, com.tiwari.studence.proto.time.TimePbOrBuilder> matchedTimeBuilder_;
    /**
     * <code>optional .com.tiwari.studence.proto.time.TimePb matchedTime = 3;</code>
     * @return Whether the matchedTime field is set.
     */
    public boolean hasMatchedTime() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .com.tiwari.studence.proto.time.TimePb matchedTime = 3;</code>
     * @return The matchedTime.
     */
    public com.tiwari.studence.proto.time.TimePb getMatchedTime() {
      if (matchedTimeBuilder_ == null) {
        return matchedTime_ == null ? com.tiwari.studence.proto.time.TimePb.getDefaultInstance() : matchedTime_;
      } else {
        return matchedTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .com.tiwari.studence.proto.time.TimePb matchedTime = 3;</code>
     */
    public Builder setMatchedTime(com.tiwari.studence.proto.time.TimePb value) {
      if (matchedTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        matchedTime_ = value;
      } else {
        matchedTimeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional .com.tiwari.studence.proto.time.TimePb matchedTime = 3;</code>
     */
    public Builder setMatchedTime(
        com.tiwari.studence.proto.time.TimePb.Builder builderForValue) {
      if (matchedTimeBuilder_ == null) {
        matchedTime_ = builderForValue.build();
      } else {
        matchedTimeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional .com.tiwari.studence.proto.time.TimePb matchedTime = 3;</code>
     */
    public Builder mergeMatchedTime(com.tiwari.studence.proto.time.TimePb value) {
      if (matchedTimeBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          matchedTime_ != null &&
          matchedTime_ != com.tiwari.studence.proto.time.TimePb.getDefaultInstance()) {
          getMatchedTimeBuilder().mergeFrom(value);
        } else {
          matchedTime_ = value;
        }
      } else {
        matchedTimeBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional .com.tiwari.studence.proto.time.TimePb matchedTime = 3;</code>
     */
    public Builder clearMatchedTime() {
      bitField0_ = (bitField0_ & ~0x00000004);
      matchedTime_ = null;
      if (matchedTimeBuilder_ != null) {
        matchedTimeBuilder_.dispose();
        matchedTimeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .com.tiwari.studence.proto.time.TimePb matchedTime = 3;</code>
     */
    public com.tiwari.studence.proto.time.TimePb.Builder getMatchedTimeBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getMatchedTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .com.tiwari.studence.proto.time.TimePb matchedTime = 3;</code>
     */
    public com.tiwari.studence.proto.time.TimePbOrBuilder getMatchedTimeOrBuilder() {
      if (matchedTimeBuilder_ != null) {
        return matchedTimeBuilder_.getMessageOrBuilder();
      } else {
        return matchedTime_ == null ?
            com.tiwari.studence.proto.time.TimePb.getDefaultInstance() : matchedTime_;
      }
    }
    /**
     * <code>optional .com.tiwari.studence.proto.time.TimePb matchedTime = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tiwari.studence.proto.time.TimePb, com.tiwari.studence.proto.time.TimePb.Builder, com.tiwari.studence.proto.time.TimePbOrBuilder> 
        getMatchedTimeFieldBuilder() {
      if (matchedTimeBuilder_ == null) {
        matchedTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.tiwari.studence.proto.time.TimePb, com.tiwari.studence.proto.time.TimePb.Builder, com.tiwari.studence.proto.time.TimePbOrBuilder>(
                getMatchedTime(),
                getParentForChildren(),
                isClean());
        matchedTime_ = null;
      }
      return matchedTimeBuilder_;
    }

    private int diff_ ;
    /**
     * <code>optional int32 diff = 4;</code>
     * @return Whether the diff field is set.
     */
    @java.lang.Override
    public boolean hasDiff() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int32 diff = 4;</code>
     * @return The diff.
     */
    @java.lang.Override
    public int getDiff() {
      return diff_;
    }
    /**
     * <code>optional int32 diff = 4;</code>
     * @param value The diff to set.
     * @return This builder for chaining.
     */
    public Builder setDiff(int value) {
      
      diff_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 diff = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDiff() {
      bitField0_ = (bitField0_ & ~0x00000008);
      diff_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.tiwari.studence.proto.match.MatchInfoPb)
  }

  // @@protoc_insertion_point(class_scope:com.tiwari.studence.proto.match.MatchInfoPb)
  private static final com.tiwari.studence.proto.match.MatchInfoPb DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tiwari.studence.proto.match.MatchInfoPb();
  }

  public static com.tiwari.studence.proto.match.MatchInfoPb getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MatchInfoPb>
      PARSER = new com.google.protobuf.AbstractParser<MatchInfoPb>() {
    @java.lang.Override
    public MatchInfoPb parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MatchInfoPb> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MatchInfoPb> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tiwari.studence.proto.match.MatchInfoPb getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

