// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: backgroundtask.proto

package com.tiwari.studence.proto.backgroundTask;

public interface BackgroundTaskIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.tiwari.studence.proto.backgroundTask.BackgroundTaskId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * just the version
   * </pre>
   *
   * <code>optional int32 taskId = 1;</code>
   * @return Whether the taskId field is set.
   */
  boolean hasTaskId();
  /**
   * <pre>
   * just the version
   * </pre>
   *
   * <code>optional int32 taskId = 1;</code>
   * @return The taskId.
   */
  int getTaskId();

  /**
   * <code>optional .com.tiwari.studence.proto.backgroundTask.TaskState taskState = 2;</code>
   * @return Whether the taskState field is set.
   */
  boolean hasTaskState();
  /**
   * <code>optional .com.tiwari.studence.proto.backgroundTask.TaskState taskState = 2;</code>
   * @return The enum numeric value on the wire for taskState.
   */
  int getTaskStateValue();
  /**
   * <code>optional .com.tiwari.studence.proto.backgroundTask.TaskState taskState = 2;</code>
   * @return The taskState.
   */
  com.tiwari.studence.proto.backgroundTask.TaskState getTaskState();

  /**
   * <code>optional .com.tiwari.studence.proto.time.TimePb taskTime = 3;</code>
   * @return Whether the taskTime field is set.
   */
  boolean hasTaskTime();
  /**
   * <code>optional .com.tiwari.studence.proto.time.TimePb taskTime = 3;</code>
   * @return The taskTime.
   */
  com.tiwari.studence.proto.time.TimePb getTaskTime();
  /**
   * <code>optional .com.tiwari.studence.proto.time.TimePb taskTime = 3;</code>
   */
  com.tiwari.studence.proto.time.TimePbOrBuilder getTaskTimeOrBuilder();

  /**
   * <code>optional bytes taskData = 4;</code>
   * @return Whether the taskData field is set.
   */
  boolean hasTaskData();
  /**
   * <code>optional bytes taskData = 4;</code>
   * @return The taskData.
   */
  com.google.protobuf.ByteString getTaskData();
}
