// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: backgroundtask.proto

package com.tiwari.studence.proto.backgroundTask;

/**
 * Protobuf enum {@code com.tiwari.studence.proto.backgroundTask.TaskState}
 */
public enum TaskState
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNKNOWN_STATE = 0;</code>
   */
  UNKNOWN_STATE(0),
  /**
   * <code>PENDING = 1;</code>
   */
  PENDING(1),
  /**
   * <code>SUCCESSFUL = 2;</code>
   */
  SUCCESSFUL(2),
  /**
   * <code>FAILED = 3;</code>
   */
  FAILED(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNKNOWN_STATE = 0;</code>
   */
  public static final int UNKNOWN_STATE_VALUE = 0;
  /**
   * <code>PENDING = 1;</code>
   */
  public static final int PENDING_VALUE = 1;
  /**
   * <code>SUCCESSFUL = 2;</code>
   */
  public static final int SUCCESSFUL_VALUE = 2;
  /**
   * <code>FAILED = 3;</code>
   */
  public static final int FAILED_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TaskState valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static TaskState forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN_STATE;
      case 1: return PENDING;
      case 2: return SUCCESSFUL;
      case 3: return FAILED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TaskState>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TaskState> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TaskState>() {
          public TaskState findValueByNumber(int number) {
            return TaskState.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.tiwari.studence.proto.backgroundTask.Backgroundtask.getDescriptor().getEnumTypes().get(0);
  }

  private static final TaskState[] VALUES = values();

  public static TaskState valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private TaskState(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.tiwari.studence.proto.backgroundTask.TaskState)
}

