// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contactDetailsPb.proto

package com.tiwari.studence.proto.contactDetails;

public interface MobileNumberPbOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.tiwari.studence.proto.contactDetails.MobileNumberPb)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.tiwari.studence.proto.contactDetails.ISDCode code = 1;</code>
   * @return The enum numeric value on the wire for code.
   */
  int getCodeValue();
  /**
   * <code>.com.tiwari.studence.proto.contactDetails.ISDCode code = 1;</code>
   * @return The code.
   */
  com.tiwari.studence.proto.contactDetails.ISDCode getCode();

  /**
   * <code>string number = 2;</code>
   * @return The number.
   */
  java.lang.String getNumber();
  /**
   * <code>string number = 2;</code>
   * @return The bytes for number.
   */
  com.google.protobuf.ByteString
      getNumberBytes();

  /**
   * <code>string canonicalNumber = 3;</code>
   * @return The canonicalNumber.
   */
  java.lang.String getCanonicalNumber();
  /**
   * <code>string canonicalNumber = 3;</code>
   * @return The bytes for canonicalNumber.
   */
  com.google.protobuf.ByteString
      getCanonicalNumberBytes();
}
