// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: teacherPb.proto

package com.tiwari.studence.proto.teacher;

/**
 * Protobuf type {@code com.tiwari.studence.proto.teacher.TeacherRefPb}
 */
public final class TeacherRefPb extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.tiwari.studence.proto.teacher.TeacherRefPb)
    TeacherRefPbOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TeacherRefPb.newBuilder() to construct.
  private TeacherRefPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TeacherRefPb() {
    dbInfoId_ = "";
    name_ = "";
    campusRefId_ = "";
    classRef_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TeacherRefPb();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tiwari.studence.proto.teacher.TeacherPbOuterClass.internal_static_com_tiwari_studence_proto_teacher_TeacherRefPb_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tiwari.studence.proto.teacher.TeacherPbOuterClass.internal_static_com_tiwari_studence_proto_teacher_TeacherRefPb_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tiwari.studence.proto.teacher.TeacherRefPb.class, com.tiwari.studence.proto.teacher.TeacherRefPb.Builder.class);
  }

  public static final int DBINFOID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object dbInfoId_ = "";
  /**
   * <code>string dbInfoId = 1;</code>
   * @return The dbInfoId.
   */
  @java.lang.Override
  public java.lang.String getDbInfoId() {
    java.lang.Object ref = dbInfoId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dbInfoId_ = s;
      return s;
    }
  }
  /**
   * <code>string dbInfoId = 1;</code>
   * @return The bytes for dbInfoId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDbInfoIdBytes() {
    java.lang.Object ref = dbInfoId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dbInfoId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CAMPUSREFID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object campusRefId_ = "";
  /**
   * <code>string campusRefId = 3;</code>
   * @return The campusRefId.
   */
  @java.lang.Override
  public java.lang.String getCampusRefId() {
    java.lang.Object ref = campusRefId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      campusRefId_ = s;
      return s;
    }
  }
  /**
   * <code>string campusRefId = 3;</code>
   * @return The bytes for campusRefId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCampusRefIdBytes() {
    java.lang.Object ref = campusRefId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      campusRefId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLASSREF_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object classRef_ = "";
  /**
   * <code>string classRef = 4;</code>
   * @return The classRef.
   */
  @java.lang.Override
  public java.lang.String getClassRef() {
    java.lang.Object ref = classRef_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      classRef_ = s;
      return s;
    }
  }
  /**
   * <code>string classRef = 4;</code>
   * @return The bytes for classRef.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClassRefBytes() {
    java.lang.Object ref = classRef_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      classRef_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dbInfoId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dbInfoId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(campusRefId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, campusRefId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(classRef_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, classRef_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dbInfoId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dbInfoId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(campusRefId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, campusRefId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(classRef_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, classRef_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tiwari.studence.proto.teacher.TeacherRefPb)) {
      return super.equals(obj);
    }
    com.tiwari.studence.proto.teacher.TeacherRefPb other = (com.tiwari.studence.proto.teacher.TeacherRefPb) obj;

    if (!getDbInfoId()
        .equals(other.getDbInfoId())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getCampusRefId()
        .equals(other.getCampusRefId())) return false;
    if (!getClassRef()
        .equals(other.getClassRef())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DBINFOID_FIELD_NUMBER;
    hash = (53 * hash) + getDbInfoId().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + CAMPUSREFID_FIELD_NUMBER;
    hash = (53 * hash) + getCampusRefId().hashCode();
    hash = (37 * hash) + CLASSREF_FIELD_NUMBER;
    hash = (53 * hash) + getClassRef().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tiwari.studence.proto.teacher.TeacherRefPb parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tiwari.studence.proto.teacher.TeacherRefPb parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tiwari.studence.proto.teacher.TeacherRefPb parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tiwari.studence.proto.teacher.TeacherRefPb parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tiwari.studence.proto.teacher.TeacherRefPb parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tiwari.studence.proto.teacher.TeacherRefPb parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tiwari.studence.proto.teacher.TeacherRefPb parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tiwari.studence.proto.teacher.TeacherRefPb parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tiwari.studence.proto.teacher.TeacherRefPb parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tiwari.studence.proto.teacher.TeacherRefPb parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tiwari.studence.proto.teacher.TeacherRefPb parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tiwari.studence.proto.teacher.TeacherRefPb parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tiwari.studence.proto.teacher.TeacherRefPb prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.tiwari.studence.proto.teacher.TeacherRefPb}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.tiwari.studence.proto.teacher.TeacherRefPb)
      com.tiwari.studence.proto.teacher.TeacherRefPbOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tiwari.studence.proto.teacher.TeacherPbOuterClass.internal_static_com_tiwari_studence_proto_teacher_TeacherRefPb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tiwari.studence.proto.teacher.TeacherPbOuterClass.internal_static_com_tiwari_studence_proto_teacher_TeacherRefPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tiwari.studence.proto.teacher.TeacherRefPb.class, com.tiwari.studence.proto.teacher.TeacherRefPb.Builder.class);
    }

    // Construct using com.tiwari.studence.proto.teacher.TeacherRefPb.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      dbInfoId_ = "";
      name_ = "";
      campusRefId_ = "";
      classRef_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tiwari.studence.proto.teacher.TeacherPbOuterClass.internal_static_com_tiwari_studence_proto_teacher_TeacherRefPb_descriptor;
    }

    @java.lang.Override
    public com.tiwari.studence.proto.teacher.TeacherRefPb getDefaultInstanceForType() {
      return com.tiwari.studence.proto.teacher.TeacherRefPb.getDefaultInstance();
    }

    @java.lang.Override
    public com.tiwari.studence.proto.teacher.TeacherRefPb build() {
      com.tiwari.studence.proto.teacher.TeacherRefPb result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tiwari.studence.proto.teacher.TeacherRefPb buildPartial() {
      com.tiwari.studence.proto.teacher.TeacherRefPb result = new com.tiwari.studence.proto.teacher.TeacherRefPb(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.tiwari.studence.proto.teacher.TeacherRefPb result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.dbInfoId_ = dbInfoId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.campusRefId_ = campusRefId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.classRef_ = classRef_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tiwari.studence.proto.teacher.TeacherRefPb) {
        return mergeFrom((com.tiwari.studence.proto.teacher.TeacherRefPb)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tiwari.studence.proto.teacher.TeacherRefPb other) {
      if (other == com.tiwari.studence.proto.teacher.TeacherRefPb.getDefaultInstance()) return this;
      if (!other.getDbInfoId().isEmpty()) {
        dbInfoId_ = other.dbInfoId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getCampusRefId().isEmpty()) {
        campusRefId_ = other.campusRefId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getClassRef().isEmpty()) {
        classRef_ = other.classRef_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              dbInfoId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              campusRefId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              classRef_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object dbInfoId_ = "";
    /**
     * <code>string dbInfoId = 1;</code>
     * @return The dbInfoId.
     */
    public java.lang.String getDbInfoId() {
      java.lang.Object ref = dbInfoId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dbInfoId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dbInfoId = 1;</code>
     * @return The bytes for dbInfoId.
     */
    public com.google.protobuf.ByteString
        getDbInfoIdBytes() {
      java.lang.Object ref = dbInfoId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dbInfoId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dbInfoId = 1;</code>
     * @param value The dbInfoId to set.
     * @return This builder for chaining.
     */
    public Builder setDbInfoId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      dbInfoId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string dbInfoId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDbInfoId() {
      dbInfoId_ = getDefaultInstance().getDbInfoId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string dbInfoId = 1;</code>
     * @param value The bytes for dbInfoId to set.
     * @return This builder for chaining.
     */
    public Builder setDbInfoIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      dbInfoId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object campusRefId_ = "";
    /**
     * <code>string campusRefId = 3;</code>
     * @return The campusRefId.
     */
    public java.lang.String getCampusRefId() {
      java.lang.Object ref = campusRefId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        campusRefId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string campusRefId = 3;</code>
     * @return The bytes for campusRefId.
     */
    public com.google.protobuf.ByteString
        getCampusRefIdBytes() {
      java.lang.Object ref = campusRefId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        campusRefId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string campusRefId = 3;</code>
     * @param value The campusRefId to set.
     * @return This builder for chaining.
     */
    public Builder setCampusRefId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      campusRefId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string campusRefId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCampusRefId() {
      campusRefId_ = getDefaultInstance().getCampusRefId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string campusRefId = 3;</code>
     * @param value The bytes for campusRefId to set.
     * @return This builder for chaining.
     */
    public Builder setCampusRefIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      campusRefId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object classRef_ = "";
    /**
     * <code>string classRef = 4;</code>
     * @return The classRef.
     */
    public java.lang.String getClassRef() {
      java.lang.Object ref = classRef_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        classRef_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string classRef = 4;</code>
     * @return The bytes for classRef.
     */
    public com.google.protobuf.ByteString
        getClassRefBytes() {
      java.lang.Object ref = classRef_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        classRef_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string classRef = 4;</code>
     * @param value The classRef to set.
     * @return This builder for chaining.
     */
    public Builder setClassRef(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      classRef_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string classRef = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearClassRef() {
      classRef_ = getDefaultInstance().getClassRef();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string classRef = 4;</code>
     * @param value The bytes for classRef to set.
     * @return This builder for chaining.
     */
    public Builder setClassRefBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      classRef_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.tiwari.studence.proto.teacher.TeacherRefPb)
  }

  // @@protoc_insertion_point(class_scope:com.tiwari.studence.proto.teacher.TeacherRefPb)
  private static final com.tiwari.studence.proto.teacher.TeacherRefPb DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tiwari.studence.proto.teacher.TeacherRefPb();
  }

  public static com.tiwari.studence.proto.teacher.TeacherRefPb getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TeacherRefPb>
      PARSER = new com.google.protobuf.AbstractParser<TeacherRefPb>() {
    @java.lang.Override
    public TeacherRefPb parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TeacherRefPb> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TeacherRefPb> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tiwari.studence.proto.teacher.TeacherRefPb getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

